Support portable installation of bootloader
openSUSE/sdbootutil pull request #106
Opened 2024-07-01 12:29 UTC by TobiPeterG

This is useful to create portable drives, so the bootloader entry isn't created permenantly.

@sysrich needs this feature for his TIK installer.

2024-07-01 13:23 UTC, aplanas commented
> This is useful to create portable drives, so the bootloader entry isn't created permenantly.

You mean that they are not registered in the EFI boot entries?

2024-07-01 13:29 UTC, aplanas requested changes

2024-07-01 13:29 UTC, aplanas commented on sdbootutil
> +	local efi_dst="/EFI/BOOT"
you defined boot_dst to have this value, should be used instead of redefining it here?

2024-07-01 13:29 UTC, aplanas commented on sdbootutil
> +	if [ -e "$prefix/$shimdir/shim.efi" ]; then
are you sure? `$shimdir` should already start with `/`

2024-07-01 13:29 UTC, aplanas commented on sdbootutil
> +		[ -n "$arg_portable" ] || install -p -D "$prefix/$shimdir/shim.efi" "$boot_root/$boot_dst/shim.efi"
I would prefer something more generic, if `shim` is missing do not install it, but do not make dependent of it is portable or not

2024-07-01 13:29 UTC, aplanas commented on sdbootutil
> +		install -p -D "$bootloader" "$boot_root/$boot_dst/grub.efi"
I think that you are adding '/' where they do not belong?

2024-07-01 13:29 UTC, aplanas commented on sdbootutil
> +		[ -n "$arg_portable" ] || install -p -D "$prefix/$shimdir/MokManager.efi" "$boot_root/$efi_dst/MokManager.efi"
Should be more generic, and if MokManager is not installed in the image, just do not use it.

Also please drop the extra `/`

2024-07-01 13:29 UTC, aplanas commented on sdbootutil
> +	[ -z "$arg_portable" ] || shim_name="BOOT${firmware_arch^^}.EFI"
This is very wrong, I think. Is the to measure the shim.efi and only the shim.efi, not the BOOT<arch>.EFI

2024-07-01 13:29 UTC, aplanas commented on sdbootutil
> +	boot_dst="/EFI/BOOT"
I do not know how a protable environment is created, but do exist /EFI/systemd or /EFI/opensuse in this case?

2024-07-01 13:39 UTC, TobiPeterG commented on sdbootutil
> +	local efi_dst="/EFI/BOOT"
When it's not a portable install, the installation process needs to write to this location anyway. And since it's accessed on multiple occasions, I exported the path to this variable

2024-07-01 13:39 UTC, TobiPeterG commented on sdbootutil
> +	if [ -e "$prefix/$shimdir/shim.efi" ]; then
Yes, I just noticed that in some places the slash is already there.
A double slash doesn't break the parsing afaik, but makes it look more consistent imo

2024-07-01 13:40 UTC, TobiPeterG commented on sdbootutil
> +		[ -n "$arg_portable" ] || install -p -D "$prefix/$shimdir/shim.efi" "$boot_root/$boot_dst/shim.efi"
Shim gets installed further down when it's a portable install, but the filename changes.

2024-07-01 13:41 UTC, TobiPeterG commented on sdbootutil
> +		install -p -D "$bootloader" "$boot_root/$boot_dst/grub.efi"
See above
Technically unnecessary, but it also doesn't break stuff and at least for me makes it more clear that it's still a path

2024-07-01 13:41 UTC, TobiPeterG commented on sdbootutil
> +		[ -n "$arg_portable" ] || install -p -D "$prefix/$shimdir/MokManager.efi" "$boot_root/$efi_dst/MokManager.efi"
I just don't install it here as it got installed in the exact same place above already when it's a portable installation

2024-07-01 13:42 UTC, TobiPeterG commented on sdbootutil
> +	[ -z "$arg_portable" ] || shim_name="BOOT${firmware_arch^^}.EFI"
The boot.efi is the shim.efi in a portable installation, just renamed for uefi to find it. :)

2024-07-01 13:43 UTC, TobiPeterG commented on sdbootutil
> +	boot_dst="/EFI/BOOT"
No, these locations don't exist, as the portable installation mode doesn't require them. Only the default /EFI/BOOT should be populated afaik

2024-07-01 14:15 UTC, aplanas commented on sdbootutil
> +	if [ -e "$prefix/$shimdir/shim.efi" ]; then
Do not change this then, will help me for the review : )

2024-07-01 14:16 UTC, aplanas commented on sdbootutil
> +		install -p -D "$bootloader" "$boot_root/$boot_dst/grub.efi"
Do not change it then

2024-07-01 14:18 UTC, TobiPeterG commented on sdbootutil
> +	local efi_dst="/EFI/BOOT"
Because if boot_dst is something different than /efi/boot efi_dst still has to be /EFI/boot

2024-07-01 14:19 UTC, aplanas commented on sdbootutil
> +		[ -n "$arg_portable" ] || install -p -D "$prefix/$shimdir/MokManager.efi" "$boot_root/$efi_dst/MokManager.efi"
My point is that if mokutil is installed, then should be copied, and if not, then the boot entry should not be registered. This make a portable system something that is a consequence of what you have installed too

For example, when building an image with KIWI, some actions should not be done but there is no need to pass an extra parameter to do that.  In that regard, I am not sure why this is really needed, because the KIWI image should be an instance of a portable system in some regard

2024-07-01 14:22 UTC, aplanas commented on sdbootutil
> +	[ -z "$arg_portable" ] || shim_name="BOOT${firmware_arch^^}.EFI"
Good point, yes. What if shim is not installed?

2024-07-01 14:23 UTC, aplanas commented on sdbootutil
> +	boot_dst="/EFI/BOOT"
In that case there is no need to pass a parameter, as can be inferred, can't it?

2024-07-01 14:27 UTC, aplanas commented on sdbootutil
> +	local efi_dst="/EFI/BOOT"
Understood, it is a constant. Then do not use a variable for that. It is more clear to see that this is a constant when it is used

2024-07-01 14:50 UTC, TobiPeterG commented on sdbootutil
> +	boot_dst="/EFI/BOOT"
How?
When installing systemd-boot for the first time, the /EFI/systemd-boot folder never exist, in both the portable and persistent case

2024-07-01 14:53 UTC, TobiPeterG commented on sdbootutil
> +		[ -n "$arg_portable" ] || install -p -D "$prefix/$shimdir/MokManager.efi" "$boot_root/$efi_dst/MokManager.efi"
How exactly would this work?
Mokmanager is always required when secure boot is wanted, isn't it?

2024-07-01 14:54 UTC, TobiPeterG commented on sdbootutil
> +		[ -n "$arg_portable" ] || install -p -D "$prefix/$shimdir/MokManager.efi" "$boot_root/$efi_dst/MokManager.efi"
> My point is that if mokutil is installed, then should be copied, and if not, then the boot entry should not be registered. This make a portable system something that is a consequence of what you have installed too
> 
> For example, when building an image with KIWI, some actions should not be done but there is no need to pass an extra parameter to do that.  In that regard, I am not sure why this is really needed, because the KIWI image should be an instance of a portable system in some regard


So on systems without shim, mokmanager will also not be available afaik, even though we might want to install systemd-boot permanently.

2024-07-01 15:08 UTC, aplanas commented on sdbootutil
> +	[ -z "$arg_portable" ] || shim_name="BOOT${firmware_arch^^}.EFI"
If shim is installed then BOOT<arch>.EFI is shim, and grub2.efi is the bootloader. If not then BOOT<arch>.EFI is the bootloader

If this is the case then the predictions should be adjusted, and the boot loader installation logic should be adjusted too. Or I am missing something?

2024-07-01 15:12 UTC, aplanas commented on sdbootutil
> +	boot_dst="/EFI/BOOT"
This is true. Would make sense to validate it in a running system? I men, if the parameter is passed but /EFI/systemd or /EFI/opensuse is present, then did something wrong happen?

2024-07-01 15:16 UTC, TobiPeterG commented on sdbootutil
> +	boot_dst="/EFI/BOOT"
Good question.
I passed a test mount, will test it in a VM later. Though I don't expect issues as I hope that boot_dst is used to determine the bootloader location everywhere.

2024-07-01 15:56 UTC, TobiPeterG commented on sdbootutil
> +	boot_dst="/EFI/BOOT"
> This is true. Would make sense to validate it in a running system? I men, if the parameter is passed but /EFI/systemd or /EFI/opensuse is present, then did something wrong happen?


Oh I just noticed: why would one test this. When the bootloader is installed as portable, why would there already be a /EFI/systemd folder?

2024-07-01 16:32 UTC, aplanas commented on sdbootutil
> +	boot_dst="/EFI/BOOT"
I was thinking in the reverse case. A normal one, but the user uses `--portable`, that will change the wrong place

2024-07-01 16:34 UTC, TobiPeterG commented on sdbootutil
> +	boot_dst="/EFI/BOOT"
Ah yes, this would change the wrong place, but I guess calling install without the --portable flag would fix it. I mean that's why it's portable, it doesn't do anything persistent.

2024-07-01 16:44 UTC, aplanas commented on sdbootutil
> +	boot_dst="/EFI/BOOT"
I am confused, changing /boot/efi/EFI/BOOT in the ESP of a running system is pretty persistent IMO ...

2024-07-01 16:50 UTC, TobiPeterG commented on sdbootutil
> +	boot_dst="/EFI/BOOT"
Yes, this part is persistent, but not in the UEFI

The worst thing I can imagine that could happen is that there are unnecessary files in /EFI/boot, but nothing that would prevent the system from booting.
But I'll test

2024-07-01 17:43 UTC, TobiPeterG commented on sdbootutil
> +	boot_dst="/EFI/BOOT"
> I am confused, changing /boot/efi/EFI/BOOT in the ESP of a running system is pretty persistent IMO ...

I tested it, what I did:
sdbootutil install
reboot
sdbootutil --portable install
reboot
sdbootutil install
reboot

The system is always bootable, after sdbootutil --portable install there are some extra files in /efi/boot, but they don't interfere with the boot process

2024-07-01 17:48 UTC, TobiPeterG commented on sdbootutil
> +	[ -z "$arg_portable" ] || shim_name="BOOT${firmware_arch^^}.EFI"
> If shim is installed then BOOT.EFI is shim, and grub2.efi is the bootloader. If not then BOOT.EFI is the bootloader
> 
> If this is the case then the predictions should be adjusted, and the boot loader installation logic should be adjusted too. Or I am missing something?

Should be fixed now, the shim.efi file is only measured when not in portable mode

2024-07-01 17:50 UTC, TobiPeterG commented
```
pcrlock \
	    lock-pe \
	    --pcrlock=/var/lib/pcrlock.d/640-boot-loader-efi-application.pcrlock.d/generated.pcrlock \
	    "${boot_root}${boot_dst}/grub.efi"
```

This is generally wrong when shim is not used, then the bootloader will not have this name.
But this should be fixed in another PR IMO

2024-07-01 19:00 UTC, aplanas requested changes

2024-07-01 19:00 UTC, aplanas commented on sdbootutil
> +	local efi_dst="/EFI/BOOT"
Please. Do not use this variable. It is confusing.

It is more clear `"$boot_root/EFI/BOOT/BOOT${firmware_arch^^}.EFI"` `"$boot_root/$efi_dst/BOOT${firmware_arch^^}.EFI"`. For one the reader can see part of the path, and for other the variable makes to believe that it can change.

2024-07-01 19:00 UTC, aplanas commented on sdbootutil
> +	if [ -e "$prefix/$shimdir/shim.efi" ]; then
Please, drop the extra `/`.  Do not include this change for this PR, we can discuss it in a different one.

2024-07-01 19:00 UTC, aplanas commented on sdbootutil
> +		[ -n "$arg_portable" ] || install -p -D "$prefix/$shimdir/shim.efi" "$boot_root/$boot_dst/shim.efi"
I still believe that this is better:

```
for i in MokManager shim; do
  install -p -D "$prefix$shimdir/$i.efi" "$boot_root$boot_dst/$i.efi" || true
done
```

or

```
for i in MokManager shim; do
  [ ! -f "$prefix$shimdir/$i.efi" ] || install -p -D "$prefix$shimdir/$i.efi" "$boot_root$boot_dst/$i.efi"
done
```

This cover your case and the case when the image does not have shim not mok manager

2024-07-01 19:00 UTC, aplanas commented on sdbootutil
> +		install -p -D "$bootloader" "$boot_root/$boot_dst/grub.efi"
For this PR do not include the `/`, lets focus only in the main feature.

2024-07-01 19:00 UTC, aplanas commented on sdbootutil
> +		[ -n "$arg_portable" ] || install -p -D "$prefix/$shimdir/MokManager.efi" "$boot_root/$efi_dst/MokManager.efi"
same than before

2024-07-01 19:00 UTC, aplanas commented on sdbootutil
> +	[ -n "$arg_portable" ] || echo "${entry##*/},openSUSE Boot Manager" | { echo -ne "\xff\xfe"; iconv -f ascii -t ucs-2le; } > "$boot_root/$boot_dst/boot.csv"
having this file does not break any portable system, right?

2024-07-01 19:00 UTC, aplanas commented on sdbootutil
> +	[ -n "$arg_no_variables" ] || [ -n "$arg_portable" ] || efibootmgr | grep -q 'Boot.*openSUSE Boot Manager' || efibootmgr -q --create --disk "$drive" --part "$partno" --label "openSUSE Boot Manager"
IMO this is the main change, can be?

2024-07-01 19:00 UTC, aplanas commented on sdbootutil
> +	[ -n "$arg_portable" ] || pcrlock \
the condition should be that `[ ! -f "${boot_root}${boot_dst}/shim.efi" ] || ` but I guess that this is not enough.

The system will measure "${boot_root}${boot_dst}/BOOT<some_arch>.EFI` so this  should be measured and not ignored

2024-07-01 19:00 UTC, aplanas commented on sdbootutil
> +	boot_dst="/EFI/BOOT"
In that case check that if `--portable` is passed, then no systemd nor opensuse is present, and error if this is the case.

It is not OK to alter /boot/efi/EFI/BOOT in non portable systems. I would argue that a more correct approach is to consider this directory when the bootloader is updated, but that will be a matter for a different PR

2024-07-01 19:01 UTC, aplanas commented
> This is generally wrong when shim is not used, then the bootloader will not have this name. But this should be fixed in another PR IMO

Yes, but until now it is save to guess that shim is used. But you are right, this needs to be changed for a more general case.

2024-07-01 21:32 UTC, TobiPeterG commented on sdbootutil
> +	local efi_dst="/EFI/BOOT"
done

2024-07-01 21:34 UTC, TobiPeterG commented on sdbootutil
> +	if [ -e "$prefix/$shimdir/shim.efi" ]; then
done

2024-07-01 21:35 UTC, TobiPeterG commented on sdbootutil
> +		[ -n "$arg_portable" ] || install -p -D "$prefix/$shimdir/shim.efi" "$boot_root/$boot_dst/shim.efi"
I don't think so. This will create a shim.efi in the /EFI/BOOT directory, even though we don't need one.

2024-07-01 21:40 UTC, TobiPeterG commented on sdbootutil
> +	boot_dst="/EFI/BOOT"
done

2024-07-01 21:41 UTC, TobiPeterG commented on sdbootutil
> +	[ -n "$arg_portable" ] || echo "${entry##*/},openSUSE Boot Manager" | { echo -ne "\xff\xfe"; iconv -f ascii -t ucs-2le; } > "$boot_root/$boot_dst/boot.csv"
AFAIK it does.
This csv tells the UEFI to create the entry when it doesn't exist already.

2024-07-01 21:42 UTC, TobiPeterG commented on sdbootutil
> +	[ -n "$arg_no_variables" ] || [ -n "$arg_portable" ] || efibootmgr | grep -q 'Boot.*openSUSE Boot Manager' || efibootmgr -q --create --disk "$drive" --part "$partno" --label "openSUSE Boot Manager"
Yes and no. This command would create the UEFI boot entry for the current system, so on reboot it is visible. The csv AFAIK is used when the entry doesn't exist yet for the UEFI to auto-create it.

2024-07-01 21:45 UTC, TobiPeterG commented on sdbootutil
> +	[ -n "$arg_portable" ] || pcrlock \
The BOOTx64.efi is the shim file in the /EFI/BOOT directory when installed as portable, there is no shim.efi to measure. We don't need it. It's the BOOTx64.efi
When shim is not available, BOOTx64.efi is the bootloader. In this case, we also don't need it. In this case, however, there is no grub.efi to be measured, so the next pcrlock command is wrong.

2024-07-03 09:16 UTC, aplanas requested changes
Thanks a lot for simplifying the changes, this helps me a lot.

2024-07-03 09:16 UTC, aplanas commented on sdbootutil
> +	[ -n "$arg_portable" ] || echo "${entry##*/},openSUSE Boot Manager" | { echo -ne "\xff\xfe"; iconv -f ascii -t ucs-2le; } > "$boot_root$boot_dst/boot.csv"
Right, seems that this file is processed by fallback.efi and added into the NVRAM

2024-07-03 09:16 UTC, aplanas commented on sdbootutil
> +	[ -n "$arg_portable" ] || pcrlock \
My point is that it is not OK to break the prediction, so this needs more work.

Your argument that because BOOT<arch>.EFI can be shim is wrong. Of course we need it. Measured boot will load BOOT<arch>.EFI and create an event log for it in PCR#4. So we need to create a component for it via `lock-pe`. 

The change is that the EFI binary will be under a different name.

For now lets assume that shim is installed. In this case the most simple change should be something like this:

```
	# 630-shim-efi-application is not part of the pcrlock standards
	# TODO: move to shim-pcrlock.rpm
        local entry="$boot_dst/shim.efi"
        [ -f "$boot_dst/BOOT${firmware_arch^^}.EFI" ] || entry="$boot_dst/BOOT${firmware_arch^^}.EFI"
	pcrlock \
	    lock-pe \
	    --pcrlock=/var/lib/pcrlock.d/630-shim-efi-application.pcrlock.d/generated.pcrlock \
	    "${boot_root}${entry}"
```

But this is not entirely correct, because the shim package maybe was not installed. Do you get the idea?

2024-07-05 15:00 UTC, TobiPeterG commented on sdbootutil
> +		install -p -D "$prefix/$shimdir/MokManager.efi" "$boot_root$boot_dst/MokManager.efi"
I refactored it, is it better now?

2024-07-05 15:00 UTC, TobiPeterG commented on sdbootutil
> +		install -p -D "$prefix$shimdir/fallback.efi" "$boot_root/EFI/BOOT/fallback.efi"
done I hope :)

2024-07-05 15:02 UTC, TobiPeterG commented on sdbootutil
> +		[ -n "$arg_portable" ] || install -p -D "$prefix/$shimdir/shim.efi" "$boot_root/$boot_dst/shim.efi"
should be done now :)

2024-07-05 15:04 UTC, TobiPeterG commented on sdbootutil
> +	[ -n "$arg_portable" ] || pcrlock \
done :)
Should probably be refactored in another PR

2024-07-05 15:08 UTC, aplanas approved these changes
LGTM, if you can fix the nits lets merge it and fix the measurements in the next PR

2024-07-05 15:08 UTC, aplanas commented on sdbootutil
> +  			[ -n "$arg_portable" ] || install -p -D "$prefix$shimdir/$i.efi" "$boot_root$boot_dst/$i.efi"
nit: initial space

2024-07-05 15:08 UTC, aplanas commented on sdbootutil
> +  			install -p -D "$prefix$shimdir/$i.efi" "$boot_root/EFI/BOOT/$i.efi"
nit: initial space

2024-07-05 15:08 UTC, aplanas commented on sdbootutil
> +    [ -f "$boot_dst/BOOT${firmware_arch^^}.EFI" ] || entry="BOOT${firmware_arch^^}.EFI"
nit: indent

2024-07-05 15:18 UTC, TobiPeterG commented
> LGTM, if you can fix the nits lets merge it and fix the measurements in the next PR

LGTM :)

2024-07-05 18:49 UTC, aplanas approved these changes

2024-07-05 18:49 UTC, merged

2024-07-05 18:50 UTC, aplanas commented
@TobiPeterG thanks!