Add show-default-entry command
openSUSE/sdbootutil pull request #112
Opened 2024-07-15 10:14 UTC by danyspin97

2024-07-15 10:33 UTC, aplanas reviewed
There is a `show-entry` command, that has `--entry-keys` to list only a subset of the elements of the entries.  This command has a VERSION parameter (for the kernel), why not to make this parameter optional and then only show the default one?

2024-07-15 10:39 UTC, aplanas commented on sdbootutil
> +}
Is a copy of list_entries, so maybe the name is confusing too. You want to list the name of the default entry but "show" is used to show the content of the entry.

If what you want is to list only the name of the default entry, then why not to add a `--only-default` parameter, and update the list_entries command?

2024-07-15 10:46 UTC, danyspin97 commented
> There is a show-entry command, that has --entry-keys to list only a subset of the elements of the entries. This command has a VERSION parameter (for the kernel), why not to make this parameter optional and then only show the default one?

I didn't want to change the usage of show-entry command, but that is definitely useful.

2024-07-15 10:50 UTC, aplanas commented
> > There is a show-entry command, that has --entry-keys to list only a subset of the elements of the entries. This command has a VERSION parameter (for the kernel), why not to make this parameter optional and then only show the default one?
> 
> I didn't want to change the usage of show-entry command, but that is definitely useful.

Right, I realized in my second comment. `show_` is to show the content of an entry, and `list_` to list the name of the entries, that is what confused me.  I still think that a full command similar to list_entries can be avoided just updating list_entries.

2024-07-15 10:54 UTC, danyspin97 commented
> Right, I realized in my second comment. show_ is to show the content of an entry, and list_ to list the name of the entries, that is what confused me. I still think that a full command similar to list_entries can be avoided just updating list_entries.

Showing the content of the default entry is good for me as well, it saves me from reading it manually. Maybe it is more useful in general than just showing the path to the default entry.

2024-07-15 11:32 UTC, danyspin97 commented on sdbootutil
> +}
I followed your advice and added a `only-default` option.

2024-07-15 11:42 UTC, aplanas requested changes

2024-07-15 11:42 UTC, aplanas commented on sdbootutil
> +        --only-default) only_default=1; shift ;;
mixing tabs / spaces

2024-07-15 11:42 UTC, aplanas commented on sdbootutil
> +			continue
Arguments are prefixed with `arg_` and defined at the beginning of the script

`[ -z "$arg_only_default" ] || continue`

2024-07-15 11:42 UTC, aplanas commented on sdbootutil
> +        --only-default) only_default=1; shift ;;
name should be arg_only_default

2024-07-16 09:36 UTC, danyspin97 commented on sdbootutil
> +			continue
Fixed.

2024-07-16 09:36 UTC, danyspin97 commented on sdbootutil
> +        --only-default) only_default=1; shift ;;
Fixed.

2024-07-16 09:41 UTC, danyspin97 commented on sdbootutil
> +			continue
> `[ -z "$arg_only_default" ] || continue`

It is okay to leave the check as it is now? I am not sure how to add that without also checking for `$isdefault` again, or use a `else` clause instead of `elif`.

2024-07-16 10:04 UTC, aplanas commented on sdbootutil
> +			continue
Yeah sure, in this case the idiom used in this project seems to be `elif [ -n "$arg_only_default" ]; then`

2024-07-16 11:13 UTC, aplanas approved these changes

2024-07-16 11:13 UTC, merged