WIP: Enroll a new recovery key
openSUSE/sdbootutil pull request #132
Opened 2024-09-09 15:43 UTC by danyspin97

Add a method to enroll a new recovery key.  The only things missing are reading the key from `systemd-cryptenroll --recovery-key` and it should be ready and testing the command.

2024-09-20 13:34 UTC, danyspin97 commented
Added the multidisk implementation.

2024-09-27 10:29 UTC, danyspin97 commented
Added the opposite flow: generated recovery PIN -> set recovery key.

2024-09-30 11:18 UTC, aplanas requested changes

2024-09-30 11:18 UTC, aplanas commented on sdbootutil
> +			if recovery_key=$(systemd-cryptenroll --wipe-slot=recovery --recovery-key --unlock-tpm2-device=auto "$dev"); then
somehow the indent is wrong here

2024-09-30 11:18 UTC, aplanas commented on sdbootutil
> +			if recovery_key=$(systemd-cryptenroll --wipe-slot=recovery --recovery-key --unlock-tpm2-device=auto "$dev"); then
Can you split the `if` and the assignment? For me is not clear if the condition is over the value of `recovery_key` or the return code of `systemd-cryptenroll`

2024-09-30 11:18 UTC, aplanas commented on sdbootutil
> +		if ! tmp_rk=$(systemd-cryptenroll --wipe-slot=recovery --recovery-key --unlock-tpm2-device=auto "$dev"); then
same

2024-09-30 11:18 UTC, aplanas commented on sdbootutil
> +		cryptsetup luksChangeKey --key-slot "$keyslot" "$dev" recovery_key < <(echo "$tmp_rk")
what if is the first enrollment? This key will not be present

Use tmpfs to store the recover key file. And I think that the echo can be removed via `<<<"$tmp_rk"`

2024-09-30 12:29 UTC, danyspin97 commented on sdbootutil
> +			if recovery_key=$(systemd-cryptenroll --wipe-slot=recovery --recovery-key --unlock-tpm2-device=auto "$dev"); then
Using `$?` is marked as warning by shellcheck though.

2024-09-30 12:31 UTC, danyspin97 commented on sdbootutil
> +		cryptsetup luksChangeKey --key-slot "$keyslot" "$dev" recovery_key < <(echo "$tmp_rk")
The key is always generated above (`systemd-cryptenroll --recovery-key`) and then changed with a new one manually, so we can safely call `luksChangeKey`.

2024-09-30 12:47 UTC, aplanas commented on sdbootutil
> +		cryptsetup luksChangeKey --key-slot "$keyslot" "$dev" recovery_key < <(echo "$tmp_rk")
I am missing something then. What I am reading is that if "recovery_key_id" is empty then it will generate a recovery key. This will the case for the first device.

But the second device does not have a recovery key keyslot, and at this point "recovery_key_id" is not empty.

2024-09-30 13:03 UTC, aplanas commented on sdbootutil
> +		cryptsetup luksChangeKey --key-slot "$keyslot" "$dev" recovery_key < <(echo "$tmp_rk")
aggg I see it now, sorry. Why not to enroll one using only cryptsetup?

2024-09-30 13:04 UTC, aplanas commented on sdbootutil
> +		if ! tmp_rk=$(systemd-cryptenroll --wipe-slot=recovery --recovery-key --unlock-tpm2-device=auto "$dev"); then
This requires that the TPM2 enrollment happen first, and there is no guarantee of that (nor that is only a FIDO2 enrollment, or a tpm2+pin)

2024-09-30 13:06 UTC, danyspin97 commented on sdbootutil
> +		cryptsetup luksChangeKey --key-slot "$keyslot" "$dev" recovery_key < <(echo "$tmp_rk")
Because this way it's systemd-cryptenroll that uses the TPM2 to unlock the device instead of doing it manually (we don't know the current password / recovery key at this time) and the user might not know either.

2024-09-30 13:13 UTC, aplanas commented on sdbootutil
> +		cryptsetup luksChangeKey --key-slot "$keyslot" "$dev" recovery_key < <(echo "$tmp_rk")
I am not sure that I agree. In the old model d-e-t generate a recovery key and use it to drive the enrollment. We should use the same approach but with this "management-key" or "enrollment-key". This key is generated during installation and used only to drive the initial enrollment, and then dropped.

This means that yes, the installed (d-e-t has this role) knows the password to use.

Depends on the TPM2 is not realistic, as TPM2 is optional. I can decide to enroll the FIDO2 key and a recovery key, or only to enroll a simple old password.

2024-09-30 13:13 UTC, danyspin97 commented on sdbootutil
> +		if ! tmp_rk=$(systemd-cryptenroll --wipe-slot=recovery --recovery-key --unlock-tpm2-device=auto "$dev"); then
> This requires that the TPM2 enrollment happen first, and there is no guarantee of that.

This is true, but we know that there is a TPM2 valid slot during first-enrollment. If the user knows the recovery key can first do the TPM2 enrollment and then enroll a new recovery key.

> FIDO2 enrollment

Maybe we can add a `--unlock` argument that defaults to `auto` and will use the first one of the available slots (TPM2, FIDO2, passphrase, recovery key) by checking `systemd-cryptenroll` output.

> or a tpm2+pin

In this case shouldn't systemd ask for the PIN directly? I don't see any other options specific for TPM2.

2024-10-28 09:58 UTC, aplanas reviewed
There are some nits appointed, and other I discovered later (error messages in certain uses cases).

I will merge and fix in a subsequent commit.

2024-10-28 09:58 UTC, aplanas approved these changes

2024-10-28 10:00 UTC, merged