Fix tracked devices detection
openSUSE/sdbootutil pull request #176
Opened 2024-12-20 23:34 UTC by TobiPeterG

Fixes #160 for me, please check if detecting tracked devices still works for you :)

2024-12-21 00:34 UTC, TobiPeterG commented
The issue is that my crypttab sometimes contains spaces and sometimes tabs and the original pattern wasn't happy with that ;)

2025-01-10 14:23 UTC, aplanas requested changes
Why not to change it to `grep -E -q "$dev[[:space:]].*x-sdbootutil.ignore" /etc/crypttab && continue`?

2025-01-10 14:31 UTC, aplanas commented
Alternative: https://github.com/openSUSE/sdbootutil/pull/188

2025-01-10 14:44 UTC, TobiPeterG commented
Closed in favor of #188

2025-01-10 14:44 UTC, closed without merging