Predict all the entries
openSUSE/sdbootutil pull request #31
Opened 2023-11-30 13:23 UTC by aplanas

Also extract the PCR values form /etc/crypttab

2023-12-06 09:46 UTC, Vogtinator commented on sdbootutil
> +		for entry in /boot/efi/loader/entries/*.conf; do
Not necessarily for this PR, but does need some discussion: Which entries should be signed?

IMO only the current + latest should allow automatic unlock.

2023-12-06 09:51 UTC, aplanas commented on sdbootutil
> +		for entry in /boot/efi/loader/entries/*.conf; do
Right. Once that all is put in place we need to revisit some of the decisions and designs. This will help a lot.

For this case I think that this decision is correct: the user should be allowed to boot in all the snapshots present in the system automatically.

For attacks that comes after exploiting CVEs present in old transactions, IMHO we should use a different mechanism: we need to re-enroll in the LUKS header a new TPM2 keyslot with a different RSA key, and all the affected snapshots deleted (with the boot entries associated with them)

But lets revisit this later.

2023-12-06 09:54 UTC, Vogtinator commented on sdbootutil
> +		for entry in /boot/efi/loader/entries/*.conf; do
IMO no. It must be possible to keep old snapshots around, even ancient and known vulnerable ones.

More than the current + latest shoudn't be necessary for automated unlock, that's all that's needed to cover normal system use + (automated) rollback in case something went wrong.

2023-12-06 09:58 UTC, Vogtinator commented on sdbootutil
> +		for entry in /boot/efi/loader/entries/*.conf; do
> For attacks that comes after exploiting CVEs present in old transactions, IMHO we should use a different mechanism: we need to re-enroll in the LUKS header a new TPM2 keyslot with a different RSA key, and all the affected snapshots deleted (with the boot entries associated with them)

Yes, to prevent downgrade attacks using old disk images it should be possible (and in certain cases done automatically) to effectively revoke access with the old keyslot data.

2023-12-12 14:13 UTC, lnussel requested changes

2023-12-12 14:13 UTC, lnussel commented on sdbootutil
> +	done <<<$(blkid -t TYPE=crypto_LUKS -o device)
That code would just take the pcrs from the first luks device, potentially unrelated to the current system. We already know the root device uuid though. So this should work:
`cryptsetup luksDump --dump-json-metadata "/dev/disk/by-uuid/$root_uuid" | jq '.tokens[]|select(.type == "systemd-tpm2")|."tpm2_pubkey_pcrs"|join(",")' -r`

2023-12-12 14:13 UTC, lnussel commented on sdbootutil
> +		for entry in /boot/efi/loader/entries/*.conf; do
`$boot_root/loader/entries`. ESP might be mounted somewhere else. However, now that pcr-oracle seems to support calculating predictions for a specific entry it seems to be logical to only process the entry sdbootutil actually just created. Updating all existing predictions all the time seems to be a surprising side effect.

2023-12-12 14:23 UTC, aplanas commented on sdbootutil
> +	done <<<$(blkid -t TYPE=crypto_LUKS -o device)
I did that on purpose. We can have multiple disks with different PCRs. The idea is that this function return multiple strings, each will be a sequence like `"a,b,c"`, that is later iterated in line 987

2023-12-12 14:24 UTC, aplanas commented on sdbootutil
> +		for entry in /boot/efi/loader/entries/*.conf; do
yes, done

2023-12-12 14:25 UTC, aplanas commented on sdbootutil
> +		for entry in /boot/efi/loader/entries/*.conf; do
The issue is that I am not sure that we will know what is created and what is destroyed. IMHO for now this is more correct: create a prediction for all the entries (or a subset, as @Vogtinator suggest)

2023-12-13 06:46 UTC, aplanas commented on sdbootutil
> +	done <<<$(blkid -t TYPE=crypto_LUKS -o device)
For clarity: it is not just taking the PCRs for the first LUKS device, it is taking the PCRs of all LUKS devices.

2023-12-13 13:30 UTC, lnussel approved these changes

2023-12-13 13:30 UTC, merged