Remove Tumbleweed version from regular entries
openSUSE/sdbootutil pull request #52
Opened 2024-02-28 22:48 UTC by TobiPeterG

This fixes an issue where tumbleweed gets updated to a new snapshot with new kernel, but the version in entries is not adapted. The version will still be visible in snapper entries, as it won't change there.
Fixes https://github.com/openSUSE/sdbootutil/issues/51

2024-02-29 07:54 UTC, lnussel commented
AFAICT this would also remove the version from microos entries

2024-02-29 09:36 UTC, TobiPeterG commented
> AFAICT this would also remove the version from microos entries

Ah alright
The comment said "on TW" that's why I thought it only applied to Tumbleweed.
Will fix it :)

2024-02-29 11:05 UTC, TobiPeterG commented
> AFAICT this would also remove the version from microos entries

Should be fixed now :)

2024-02-29 15:39 UTC, lnussel requested changes

2024-02-29 15:39 UTC, lnussel commented on sdbootutil
>  	fi
```
if is_transactional; then
  add_version_to_title
elif subvol_is_ro "$subvol"; then
  ...
fi
```
And while you are at it, there is also #49 ... :-)

2024-02-29 16:15 UTC, TobiPeterG commented on sdbootutil
>  	fi
refactored it :)

#49 is probably caused by something else. I think I know the issue:
for i in /etc/os-release /usr/lib/os-release; do
	[ -f "$i" ] || continue
	eval $(sed -ne '/^[A-Z_]\+=/s/^/os_release_/p' < "$i")
	break
done
looks for the os-release in the current snapshot, not the new one

2024-02-29 16:18 UTC, TobiPeterG commented on sdbootutil
>  	fi
similarly, we're reading the current machine-id
[ -s /etc/machine-id ] && read -r machine_id < /etc/machine-id

Is there any way it changes between snapshots?

2024-02-29 16:32 UTC, lnussel commented on sdbootutil
>  	fi
the one in etc is just compat. The canonical one should be in /usr. Machine-id could change I guess but is unexpected. Would mean it's a different instance of the same OS. If we make everything snapshot specific we could deploy arbitrary states though. Anyway, looks like a bigger change, you don't have to to do that in the scope here indeed.

2024-03-01 10:53 UTC, TobiPeterG commented on sdbootutil
>  	fi
Can this be merged then or are there still open items?

2024-03-04 14:58 UTC, merged