Add basic boot assessment
openSUSE/sdbootutil pull request #53
Opened 2024-02-28 23:51 UTC by TobiPeterG

This adds 3 attempts to all boot entries. If all attempts fail, it will automatically get marked unbootable. This commit also adds logic to all parts that access the conf files to detect them, no matter the state.

However, as listed here: https://systemd.io/AUTOMATIC_BOOT_ASSESSMENT/ we still need to add the adequate services as Requires= to boot-complete.target. This way, network etc. can also be assessed.
Boot entries will be assessed until they boot successfully once.

Please test the changes here

2024-02-29 07:50 UTC, lnussel requested changes

2024-02-29 07:50 UTC, lnussel commented on sdbootutil
> +	for file in "${conf_dir}/${entry_token}-${kernel_version}-${snapshot}"*.conf; do
Hmm, you check whether it's easier to use jq for that? we have `update_entries_for_snapshot` and in the json output systemd does the parsing of the counter for us:

```
                "id" : "opensuse-tumbleweed-6.7.5-1-kvmsmall-1.conf",
                "path" : "/boot/efi/loader/entries/opensuse-tumbleweed-6.7.5-1-kvmsmall-1+3.conf",
```

2024-03-02 21:39 UTC, TobiPeterG commented on sdbootutil
> +	for file in "${conf_dir}/${entry_token}-${kernel_version}-${snapshot}"*.conf; do
Adapted the code, hope it's what you had in mind :)

2024-03-04 14:37 UTC, lnussel commented on sdbootutil
> +	while IFS= read -r path; do
you didn't test this

2024-03-04 14:40 UTC, TobiPeterG commented on sdbootutil
> +	while IFS= read -r path; do
I did, I copied the code, set the necessary variables and echo'ed the output 

Have I missed something?

2024-03-04 14:40 UTC, TobiPeterG commented on sdbootutil
> +	while IFS= read -r path; do
I did, I copied the code, set the necessary variables and echo'ed the output 

Have I missed something?

2024-03-04 21:22 UTC, TobiPeterG commented on sdbootutil
> +	while IFS= read -r path; do
Ah now I know what you mean, fixed it (and tested it properly) :)

2024-03-05 10:09 UTC, lnussel requested changes

2024-03-05 10:09 UTC, lnussel commented on sdbootutil
> +		'.[] | select(.id | test("^" + $token + "-" + $version + "-" + $snapshot + ".conf$")).id as $id | "\($id)\t\(.path)"' < "$entryfile")
```
local id="$entry_token-$kernel_version-$snapshot.conf"
...
jq -r --arg id "$id" '.[]| select(.id == $id)|.path'
```
However, you are using variables here that are not passed as argument and are not global either.

Since the function is used to find the config file in order to parse it for initrd settings, it may just as well do the parsing and return the initrds found?

2024-03-05 10:09 UTC, lnussel commented on sdbootutil
> +	run_command_output bootctl unlink "$conf_id"
IIRC unlink doesn't need the counter. Just pass the id without counter and it would find one that has a counter

2024-03-05 11:02 UTC, TobiPeterG commented on sdbootutil
> +	if [ ! -s "$entryfile" ]; then
It's just copied from the list_entries function. Is the check not neccessary here?

2024-03-05 11:03 UTC, TobiPeterG commented on sdbootutil
> +	run_command_output bootctl unlink "$conf_id"
oh you're right, the ID shouldn't change :)

2024-03-05 11:10 UTC, TobiPeterG commented on sdbootutil
> +		'.[] | select(.id | test("^" + $token + "-" + $version + "-" + $snapshot + ".conf$")).id as $id | "\($id)\t\(.path)"' < "$entryfile")
I guess the function could be used to also find initrds, but this would be two seperate tasks for one function (identify entry file + find initrds). For reusability purposes I only included finding configuration files.

However, if wanted, I can remove the function and move the logic to the reuse_initrd function as this is currently the only one using the function.

2024-03-06 11:55 UTC, lnussel commented on sdbootutil
> +		'.[] | select(.id | test("^" + $token + "-" + $version + "-" + $snapshot + ".conf$")).id as $id | "\($id)\t\(.path)"' < "$entryfile")
it's fine to only limit it to the path for now for simplicity I think, given that the entry is parsed elsewhere too. The parameters need to be tuned to not rely on the calling scope. Ie could just pass the id and let the function return the path.
Something like local conf="$(get_entry_path "$entry_token-$kernel_version-$snapshot.conf")"

2024-03-06 22:30 UTC, TobiPeterG commented on sdbootutil
> +		'.[] | select(.id | test("^" + $token + "-" + $version + "-" + $snapshot + ".conf$")).id as $id | "\($id)\t\(.path)"' < "$entryfile")
done :)

2024-03-14 12:46 UTC, lnussel commented on sdbootutil
> +	if [ ! -s "$entryfile" ]; then
it's not useful either way I guess. It means the list wouldn't get updated when the file exists.

2024-03-14 13:14 UTC, lnussel requested changes

2024-03-14 13:14 UTC, lnussel commented on sdbootutil
> +		update_entries_for_snapshot "$snapshot"
$snapshot is not an argument of this function

2024-03-14 13:14 UTC, lnussel commented on sdbootutil
> +		loader_entry="$boot_root/loader/entries/$entry_token-$kernel_version-$snapshot+3.conf"
kernel-install reads the counter from /etc/kernel/tries, we need to mirror this

2024-03-21 20:33 UTC, TobiPeterG commented on sdbootutil
> +		update_entries_for_snapshot "$snapshot"
ah you're right. I split the parameters into kernel_version and snapshot again to be able to get the entries for the snapshots easily and construct the id with them :)

2024-03-21 20:50 UTC, TobiPeterG commented on sdbootutil
> +		loader_entry="$boot_root/loader/entries/$entry_token-$kernel_version-$snapshot+3.conf"
You're right, done :)

2024-03-21 20:51 UTC, TobiPeterG commented on sdbootutil
> +	if [ ! -s "$entryfile" ]; then
removed :)

2024-03-25 17:37 UTC, lnussel requested changes
needs rebase

2024-03-25 17:37 UTC, lnussel commented on sdbootutil
> +			tries=$(< /etc/kernel/tries head -n 1 | tr -d '\n')
use read

2024-03-25 17:37 UTC, lnussel commented on sdbootutil
> +    		tries=0
`tries=`

2024-03-25 17:37 UTC, lnussel commented on sdbootutil
> +		local tries=0
`local tries`

2024-03-25 17:37 UTC, lnussel commented on sdbootutil
> +		loader_entry="$boot_root/loader/entries/$entry_token-$kernel_version-$snapshot"
`loader_entry="$boot_root/loader/entries/$entry_token-$kernel_version-$snapshot${tries:+-$tries}.conf"`

2024-03-27 20:01 UTC, TobiPeterG commented on sdbootutil
> +		loader_entry="$boot_root/loader/entries/$entry_token-$kernel_version-$snapshot"
all done :)

2024-03-27 20:02 UTC, TobiPeterG commented
rebased as well :)

2024-03-28 09:53 UTC, lnussel requested changes

2024-03-28 09:53 UTC, lnussel commented on sdbootutil
> +    		tries=
missing tab? You could also do that in one line btw

2024-03-28 09:53 UTC, lnussel commented on sdbootutil
> +		loader_entry="$boot_root/loader/entries/$entry_token-$kernel_version-$snapshot${tries:++$tries}.conf"
here you are reverting the optional snapshot

2024-03-28 09:53 UTC, lnussel commented on sdbootutil
> +	conf=$(find_conf_file "$kernel_version" "${snapshot}")
should have extra quotiong around the `$(..)`. I assume shellcheck complains about that. Same below

2024-03-28 09:53 UTC, lnussel commented on sdbootutil
> +	if [ $find_conf_status -eq 0 ]; then
also quoting

2024-03-28 09:53 UTC, lnussel commented on sdbootutil
> +			find_conf_status=$?
quoting

2024-03-29 13:14 UTC, TobiPeterG commented on sdbootutil
> +    		tries=
whops, no, was just a mix of tabs and spaces, so it looked right for me. Fixed :)

2024-03-29 13:15 UTC, TobiPeterG commented on sdbootutil
> +		loader_entry="$boot_root/loader/entries/$entry_token-$kernel_version-$snapshot${tries:++$tries}.conf"
fixed

2024-03-29 13:16 UTC, TobiPeterG commented on sdbootutil
> +	conf=$(find_conf_file "$kernel_version" "${snapshot}")
Well, my shellcheck doesn't complain, added them

2024-03-29 13:17 UTC, TobiPeterG commented on sdbootutil
> +	if [ $find_conf_status -eq 0 ]; then
done

2024-03-29 13:17 UTC, TobiPeterG commented on sdbootutil
> +			find_conf_status=$?
done

2024-04-02 12:15 UTC, merged