Misc fixes
openSUSE/sdbootutil pull request #54
Opened 2024-02-29 07:34 UTC by lnussel

2024-02-29 07:51 UTC, aplanas requested changes

2024-02-29 07:51 UTC, aplanas commented on sdbootutil
> +	/usr/lib/systemd/systemd-pcrlock \
should the stdout be redirected to /dev/null in all the calls? This will break the screen

2024-02-29 07:51 UTC, aplanas commented on sdbootutil
> +		/usr/lib/systemd/systemd-pcrlock lock-secureboot-policy --force || true
this --force is not part of 256?

2024-02-29 07:51 UTC, aplanas commented on sdbootutil
> +	fi
for consistency this should be done later, at least after the shim

2024-02-29 07:51 UTC, aplanas commented on sdbootutil
> +	/etc/systemd/tpm2-pcr-signature.json
?

missing rm?

2024-02-29 07:51 UTC, aplanas commented on sdbootutil
> +
as commented I do not like this, we should have a single PCR list as a source or truth, so it should be shared between both solutions

2024-02-29 08:05 UTC, lnussel commented on sdbootutil
> +	/etc/systemd/tpm2-pcr-signature.json
true

2024-02-29 08:08 UTC, lnussel commented on sdbootutil
> +	fi
k

2024-02-29 08:09 UTC, lnussel commented on sdbootutil
> +	/usr/lib/systemd/systemd-pcrlock \
I think the output of pcrlock needs to be reduced upstream. it's too verbose by default

2024-02-29 08:12 UTC, aplanas commented on sdbootutil
> +		/usr/lib/systemd/systemd-pcrlock lock-secureboot-policy --force || true
lets remove it then

2024-02-29 08:13 UTC, aplanas commented on sdbootutil
> +	/usr/lib/systemd/systemd-pcrlock \
it is both: too verbose and too short, but the point still remains, should be > /dev/null maybe?

2024-02-29 08:23 UTC, lnussel commented on sdbootutil
> +	/usr/lib/systemd/systemd-pcrlock \
I don't think so. the reason I removed the logging was that I didn't see any output at all.

2024-02-29 09:26 UTC, aplanas commented on sdbootutil
> +	/usr/lib/systemd/systemd-pcrlock \
right, this is why I added it, so I can add the debug envar and see the full output of pcrlock without breaking the screen

this change will break the screen in debug mode and in normal mode

2024-03-04 12:58 UTC, lnussel commented on sdbootutil
> +	/usr/lib/systemd/systemd-pcrlock \
we could set SYSTEMD_LOG_LEVEL=warning if unset for the duration of pcrlock to avoid excessive output

2024-03-04 13:31 UTC, lnussel commented on sdbootutil
> +	/usr/lib/systemd/systemd-pcrlock \
What about `SYSTEMD_LOG_LEVEL=debug SYSTEMD_LOG_TARGET=journal`?

2024-03-04 13:33 UTC, aplanas commented on sdbootutil
> +	/usr/lib/systemd/systemd-pcrlock \
but this does not cut the normal stdout IIUC

2024-03-04 13:43 UTC, lnussel commented on sdbootutil
> +	/usr/lib/systemd/systemd-pcrlock \
That's why I thought about setting SYSTEMD_LOG_LEVEL=warning (unless SYSTEMD_LOG_LEVEL is set from outside). That way we'd see pcrlock warnings and errors on the tty while allowing to increase verbosity and log target via env vars.
In any case IMO the goal should be to reduce log output of pcrlock upstream in the first place. Those informative messages kind of make sense in the automatic mode it has right now. If we force it to  use specified pcrs however, there's not reason for pcrlock to report that it actually did what it was asked to do :)

2024-03-04 14:00 UTC, aplanas commented on sdbootutil
> +	/usr/lib/systemd/systemd-pcrlock \
ok then good for me to set `SYSTEMD_LOG_LEVEL=warning`!

2024-03-05 09:21 UTC, merged