Use new os-release and machine-id files
openSUSE/sdbootutil pull request #55
Opened 2024-03-02 22:46 UTC by TobiPeterG

This fixes an issue where the os-release file has been updated, but the old one is still used by sdbootutil to generate the new entries.
This should fix https://github.com/openSUSE/sdbootutil/issues/49

2024-03-04 14:07 UTC, lnussel commented on sdbootutil
> +	"${subvol#${subvol_prefix}}/etc/os-release"
subvol is local to some fuctions. I don't think that works. We'd need to defer evaluating os-relase to when we actually need it I think. Looking at the code that might mean calling bootctl twice as there's information such as the ESP that is hopefully generic and others like the entry token that might be specific to a given snapshot

2024-03-04 20:08 UTC, TobiPeterG commented on sdbootutil
> +	"${subvol#${subvol_prefix}}/etc/os-release"
Whoops, you're right.
I thought I could use the root snapshot, but this doesn't make any sense at all.
Sorry.
I'll think about a new solution :)

2024-03-04 20:30 UTC, TobiPeterG commented on sdbootutil
> +	"${subvol#${subvol_prefix}}/etc/os-release"
I've extracted the os_release and machine_id read part into their own functions that are called before they are accessed. However, this is a naive implementation and requires a dev to make sure to update the os_release and machine_id before using them.

However, this should now *actually* solve the issue :)

2024-03-05 09:33 UTC, lnussel requested changes

2024-03-05 09:33 UTC, lnussel commented on sdbootutil
> +		"/etc/os-release"
passing the snapshot is mandatory and a snapshot must have an os-release file so the fallback to / shouldn't be needed, right?

2024-03-05 09:33 UTC, lnussel commented on sdbootutil
> +		"/etc/machine-id"
same here

2024-03-05 09:33 UTC, lnussel commented on sdbootutil
> +	set_os_release $snapshot
quoting. Try shellcheck :-) If you are on vim, I'm using vim-plugin-airline and vim-plugin-ale (and vim-plugin-editorconfig)

2024-03-05 09:33 UTC, lnussel commented on sdbootutil
> +	set_os_release $snapshot
also, I think we may want to call settle_entry_token exclusively here

2024-03-05 09:33 UTC, lnussel commented on sdbootutil
> +	set_machine_id $snapshot
quoting

2024-03-05 09:33 UTC, lnussel commented on sdbootutil
> +	set_machine_id $snapshot
quoting.
If we call settle_entry_token as mentioned above, it could probably mandate that eg. machine_id is set before it gets called

2024-03-05 09:36 UTC, TobiPeterG commented on sdbootutil
> +		"/etc/os-release"
In theory, you are right. I thought about cases where the user maybe made an oopsy and the file has been deleted in the snapshot or isn't there for some reason.
Also, I wanted to make it as robust as possible. But I can remove them if wanted :)

2024-03-05 09:45 UTC, TobiPeterG commented on sdbootutil
> +	set_os_release $snapshot
I use VS Code and installed a bash plugin, but that wasn't really helpful. Installed shellcheck now, this actually displays anything useful now :)
Fixed quoting, call settle_entry_token here now instead :)

2024-03-05 09:48 UTC, TobiPeterG commented on sdbootutil
> +	set_machine_id $snapshot
I am a little unsure which call to action results from this tbh :sweat_smile:

2024-03-06 10:21 UTC, lnussel requested changes

2024-03-06 10:21 UTC, lnussel commented on sdbootutil
> +settle_entry_token "$root_snapshot"
I guess we don't need it here anymore then

2024-03-06 10:21 UTC, lnussel commented on sdbootutil
> +		"/etc/os-release"
without os-release the snapshot would be broken

2024-03-06 22:42 UTC, TobiPeterG commented on sdbootutil
> +settle_entry_token "$root_snapshot"
A few lines below we check if entry_token exists. So currently needed, but is the check still useful?

2024-03-06 22:43 UTC, TobiPeterG commented on sdbootutil
> +		"/etc/os-release"
confirmed, a system without os-release file doesn't boot :D

Removed it :)

2024-03-06 22:44 UTC, TobiPeterG commented on sdbootutil
> +		"/etc/machine-id"
done :)

2024-03-12 12:45 UTC, lnussel commented on sdbootutil
> +	set_machine_id $snapshot
`$snapshot -> "$snapshot"`
or
`[ -n "$machine_id" ] || err ..`

2024-03-12 12:48 UTC, lnussel commented on sdbootutil
> +		"") [ -n "$entry_token" ] || entry_token="$machine_id" ;;
Not sure why I wrote it like this originally. Now it seems empty should just be `auto`

2024-03-12 13:46 UTC, TobiPeterG commented on sdbootutil
> +	set_machine_id $snapshot
the quoting is already fixed :)

2024-03-12 13:47 UTC, TobiPeterG commented on sdbootutil
> +	set_machine_id $snapshot
added the check :)

2024-03-12 14:02 UTC, TobiPeterG commented on sdbootutil
> +settle_entry_token "$root_snapshot"
removed the check, added settle_entry_token in every function where we use the $entry_token variable

2024-03-12 14:05 UTC, TobiPeterG commented on sdbootutil
> +		"") [ -n "$entry_token" ] || entry_token="$machine_id" ;;
well, I can't remove the line `"") [ -n "$entry_token" ] || entry_token="$machine_id" ;;` as then e.g remove-all-kernels fails, so it seems to do something

2024-03-14 09:58 UTC, lnussel commented on sdbootutil
> +		"") [ -n "$entry_token" ] || entry_token="$machine_id" ;;
I mean merging it with the "auto" branch
`""|auto)`

2024-03-21 20:57 UTC, TobiPeterG commented on sdbootutil
> +		"") [ -n "$entry_token" ] || entry_token="$machine_id" ;;
done :)

2024-03-26 09:56 UTC, lnussel commented
looks ok but needs rebase

2024-03-27 19:20 UTC, TobiPeterG commented
quick question: In line 429 and 427, -$snapshot is used, even though it might not be set. Is this intended?
e.g.: local conf="$boot_root/loader/entries/$entry_token-$kernel_version-$snapshot.conf"

2024-03-28 09:55 UTC, lnussel commented
> quick question: In line 429 and 427, -$snapshot is used, even though it might not be set. Is this intended? e.g.: local conf="$boot_root/loader/entries/$entry_token-$kernel_version-$snapshot.conf"

Should most likely be `${snapshot:--$snapshot}` always

2024-03-28 09:57 UTC, lnussel requested changes

2024-03-28 09:57 UTC, lnussel commented on sdbootutil
> +	[ -n "$snapshot" ] && subvol="${subvol_prefix}/.snapshots/${snapshot}/snapshot"
should be `assert()` style logic in one liners. Ie
`[ -z "$something" ] || ...`

2024-03-29 13:01 UTC, TobiPeterG commented on sdbootutil
> +	[ -n "$snapshot" ] && subvol="${subvol_prefix}/.snapshots/${snapshot}/snapshot"
done

2024-04-02 16:08 UTC, lnussel commented
https://github.com/openSUSE/sdbootutil/pull/78

2024-04-04 07:05 UTC, merged