Add bash completions
openSUSE/sdbootutil pull request #62
Opened 2024-03-05 00:47 UTC by TobiPeterG

This will complete started commands and provide a list of possible commands and options.

Closes https://github.com/openSUSE/sdbootutil/issues/61

2024-03-05 09:21 UTC, lnussel commented
I'd probably add a hidden function to sdbootutil that can be eval'd from the completion script to avoid duplicating all that code

2024-03-05 10:59 UTC, TobiPeterG commented
> I'd probably add a hidden function to sdbootutil that can be eval'd from the completion script to avoid duplicating all that code

I've looked a bit into how bash completion works and it seems like the bash completion has to happen in the same shell context. So I can A) source the sdbootutil script, but that would execute the functions that might fail as the bash completion can be called as non-super user
B) call a function in sdbootutil where I echo the recommendations, but that would also not be a nice solution
C) Create two functions in sdbootutil that are callable that return the architecture/image name and kernels in the current snapshot.

Or do you have a different idea?
I agree that the code duplication isn't nice

2024-03-05 14:42 UTC, lnussel commented
something like `eval $(sdbootutil _print_bash_completion_data)`

2024-03-05 17:40 UTC, TobiPeterG commented
> something like `eval $(sdbootutil _print_bash_completion_data)`

I've tried to implement this. I couldn't test it yet though, but please tell me if this is what you had in mind :)
The code also isn't nice yet, it's just thought as a concept currently :)

2024-03-06 10:15 UTC, lnussel requested changes

2024-03-06 10:15 UTC, lnussel commented on sdbootutil
> +_sdbootutil_completion()
this function still belongs into the separate completion script

2024-03-06 10:15 UTC, lnussel commented on sdbootutil
> +	if [[ -z "$1" ]]; then
A single [ is sufficient here

2024-03-06 10:15 UTC, lnussel commented on sdbootutil
> +find_image()
not really finding anything. determining the kernel image name.

2024-03-06 10:15 UTC, lnussel commented on sdbootutil
> +	local opts_arguments="--esp-path --arch --entry-token --image"
those bits could be extracted from existing information to avoid duplicating it. eg we could put the long options of getopt into a separate variable and parse that for completion purposes.

Similarly the supported command list could be put into an associative array. The existing case statement is no longer cool I think.

2024-03-06 23:40 UTC, TobiPeterG commented on sdbootutil
> +	if [[ -z "$1" ]]; then
fixed

2024-03-06 23:40 UTC, TobiPeterG commented on sdbootutil
> +_sdbootutil_completion()
done :)

2024-03-06 23:40 UTC, TobiPeterG commented on sdbootutil
> +find_image()
renamed :)

2024-03-07 00:16 UTC, TobiPeterG commented on sdbootutil
> +	local opts_arguments="--esp-path --arch --entry-token --image"
done, did a bit of testing, seems to work :)
Please check if it works for you :)

2024-03-14 12:56 UTC, lnussel requested changes

2024-03-14 12:56 UTC, lnussel commented on sdbootutil
> +	if [ "$1" == "completion" ]; then
only the $1 != completion needed here

2024-03-14 12:56 UTC, lnussel commented on sdbootutil
> +			chksum="$kv"
that's nasty, don't do that :) As you are only interested in the kernel versions, not the checkums. maybe it makes sense to run the loop separately in the completion script after all

2024-03-14 12:56 UTC, lnussel commented on sdbootutil
> +	commands_interactive="kernels snapshots entries"
use associative arrays!

2024-03-14 12:56 UTC, lnussel commented on sdbootutil
> +if [[ -z "$1" || " $commands_interactive " =~ " $1 " ]]; then
no way. use associative arrays

2024-03-21 21:00 UTC, TobiPeterG commented on sdbootutil
> +	if [ "$1" == "completion" ]; then
done :)

2024-03-21 21:30 UTC, TobiPeterG commented on sdbootutil
> +	commands_interactive="kernels snapshots entries"
done

2024-03-21 21:31 UTC, TobiPeterG commented on sdbootutil
> +if [[ -z "$1" || " $commands_interactive " =~ " $1 " ]]; then
done
Also removed the if else at the end and replaced it with a case statement

2024-03-21 21:51 UTC, TobiPeterG commented on sdbootutil
> +			chksum="$kv"
done, moved a simplified version to the completion script

2024-03-26 09:51 UTC, lnussel requested changes

2024-03-26 09:51 UTC, lnussel commented on completion/sdbootutil
> +find_kernels()
duplicated from sdbootutil?

2024-03-26 09:51 UTC, lnussel commented on sdbootutil
> +	declare -gA command_types=(
```
  declare -A commands=(
    [install]=
    [add-kernel]=kernel
    [entries]=interactive
    ...
)
```
you can test for existance of a key eg using `[ ${commands[$cmd]+yes} ]`

2024-03-26 09:51 UTC, lnussel commented on sdbootutil
> +if [[ -z "$1" || ${command_types["$1"]} == "command_interactive" ]]; then
`[ -z "$1" ] || [ "${commands[$1]}" = 'interactive' ]`

2024-03-26 09:51 UTC, lnussel commented on sdbootutil
> +		[--no-random-seed]="option" [--all]="option"
this is duplicating the getopt argument still
super fancy code to parse it:
```
opts_long="help,flicker,verbose,esp-path:,entry-token:,arch:,image:,no-variables,no-reuse-initrd,no-random-seed,all"
declare -A opts_long_dict
parse_opts()
{
        IFS=, eval set -- \$opts_long
        eval "${@//*/opts_long_dict[&]=}"
}
parse_opts
```

2024-03-26 09:51 UTC, lnussel commented on completion/sdbootutil
> +eval "$(sdbootutil _print_bash_completion_data)"
this should be done once inside the _sdbootutil_completion function I guess to avoid the code from running right when a new shell is started

2024-03-26 09:51 UTC, lnussel commented on completion/sdbootutil
> +		if [[ " --arch " == " $word " ]]; then
no need for [[ here and many other places

2024-04-07 20:28 UTC, TobiPeterG commented on completion/sdbootutil
> +find_kernels()
Above you said it might make sense to run the loop in the script. As the function in sdbootutil calculates the checksum etc., it wouldn't really be nice code.

2024-04-09 17:40 UTC, TobiPeterG commented on sdbootutil
> +		[--no-random-seed]="option" [--all]="option"
I don't think this is really required. The completion script just needs the option names, not the parsing,

2024-04-09 17:40 UTC, TobiPeterG commented on completion/sdbootutil
> +eval "$(sdbootutil _print_bash_completion_data)"
done

2024-04-09 18:01 UTC, TobiPeterG commented on completion/sdbootutil
> +		if [[ " --arch " == " $word " ]]; then
done :)

2024-04-17 07:44 UTC, lnussel submitted a review, later dismissed
almost there

2024-04-17 07:44 UTC, lnussel commented on sdbootutil
> +	declare -g opts_long="help,flicker,verbose,esp-path,entry-token,arch,image,no-variables,no-reuse-initrd,no-random-seed,all"
lacks colons for arguments. A fancy way would be to use an associative array here too. The value could be either empty (no argument) or a function name for the completion of the argument. opts_long then consists of the keys of the array with colons appended to the keys that have a completion function defined.

2024-05-20 13:37 UTC, TobiPeterG commented on sdbootutil
> +	declare -g opts_long="help,flicker,verbose,esp-path,entry-token,arch,image,no-variables,no-reuse-initrd,no-random-seed,all"
Sorry for the delay, please check if this is now what you are looking for :)

2024-06-18 08:41 UTC, TobiPeterG commented
@aplanas can you have a look at this one please? :)

2024-07-01 18:38 UTC, TobiPeterG commented on completion/sdbootutil
> +	for fn in ""/usr/lib/modules/*/"$image"; do
I removed the first two quote signs, but this seems to be correct. At least shellcheck doesn't like it otherwise.

2024-07-01 18:38 UTC, TobiPeterG commented on sdbootutil.spec
> +mkdir -p %{buildroot}%{_datadir}/bash-completion/completions
removed

2024-07-01 18:39 UTC, TobiPeterG commented on sdbootutil
> +		install_bootloader "${2:-$root_snapshot}" ;;
done

2024-07-01 18:40 UTC, TobiPeterG commented on sdbootutil
> +	fi
done

2024-07-01 18:40 UTC, TobiPeterG commented on sdbootutil
> +	if [[ -n "${arch_image_map[$firmware_arch]}" ]]; then
done

2024-07-01 18:45 UTC, TobiPeterG commented on completion/sdbootutil
> +complete -F _sdbootutil_completion sdbootutil
done

2024-07-01 18:55 UTC, TobiPeterG commented on sdbootutil
> +	declare -f set_image_name
Why exactly is this neccessary?
Previously, these global variables were already in the sdbootutil script set, these functions just make sure they are also accessible in the bash completion script.
We can't just export the $image variable as the options given to sdbootutil might change it or the architecture, which needs to then reset the image to the new name.
We definitely need the function available in the completion script.

2024-07-01 18:57 UTC, TobiPeterG commented on completion/sdbootutil
> +	eval "$(sdbootutil _print_bash_completion_data)"
At first I did that, Ludwig didn't like it :D

When I remember correctly, these completions scripts get executed once when a new shell is created. This would mean that sdbootutil gets called automatically by bash, even when there is no intend to call it manually as user.
This fixes that.

2024-07-01 19:00 UTC, TobiPeterG commented on completion/sdbootutil
> +	_get_comp_words_by_ref -n : cur prev words cword
Hmm. The completion script wouldn't be called without the package afaik, so not including it as required doesn't break anything I guess.

2024-07-01 19:01 UTC, TobiPeterG commented on sdbootutil.spec
> +%dir %{_datadir}/bash-completion
see above.
I guess that including it in the regular package shouldn't break anything, even when bash-completion is not installed.
If you want to, though, I can of course place this in its own package. It would become a long list of packages if we support other shells in the future as well :D

2024-07-01 19:03 UTC, aplanas commented on completion/sdbootutil
> +	for fn in ""/usr/lib/modules/*/"$image"; do
Interesting. But ""/... I parsed as "append the empty string to /..". It is not 'wrong', so shellcheck cannot complain, but I guess that it is not what you want to do?

2024-07-01 19:05 UTC, TobiPeterG commented on completion/sdbootutil
> +	done
Yes, you are right :)
Done

2024-07-01 19:05 UTC, TobiPeterG commented on completion/sdbootutil
> +	done
done

2024-07-01 19:06 UTC, TobiPeterG commented on completion/sdbootutil
> +		if [ -n "${commands["$word"]+yes}" ]; then
I think yes.
It should match all commands with a key, not only those with a value

2024-07-01 19:09 UTC, aplanas commented on sdbootutil
> +	declare -f set_image_name
I do not follow ... the architecture cannot change on the running system. Once the function in sdbootutil knows the value of those variables, that will not change for this completion session.

2024-07-01 19:10 UTC, TobiPeterG commented on completion/sdbootutil
> +	for fn in ""/usr/lib/modules/*/"$image"; do
No, it's not. But as it seems, we can't just use single quotes around everything as this would run only once (at least shellcheck says that)

2024-07-01 19:12 UTC, aplanas commented on sdbootutil.spec
> +%dir %{_datadir}/bash-completion
I think that should be a subpackage, in case that others use zsh, fish or others

2024-07-01 19:14 UTC, aplanas commented on completion/sdbootutil
> +	_get_comp_words_by_ref -n : cur prev words cword
That is OK, but I was thinking in the reverse case. If this is a subpackage and a user install this subpackage, then they also want to install the bash-completion package too.

2024-07-01 19:16 UTC, aplanas commented on completion/sdbootutil
> +	for fn in ""/usr/lib/modules/*/"$image"; do
Ah, so there is a complain for `"/usr/lib/modules/*/$image";` from shellcheck! What is the ID?

2024-07-01 21:49 UTC, TobiPeterG commented on completion/sdbootutil
> +	for fn in ""/usr/lib/modules/*/"$image"; do
yes.
https://www.shellcheck.net/wiki/SC2066

2024-07-01 21:50 UTC, TobiPeterG commented on sdbootutil
> +	declare -f set_image_name
There is an option --arch to set the architecture manually and --image to set the image name manually..
This option might be used, so we need to change the image name.

2024-07-01 21:54 UTC, TobiPeterG commented on sdbootutil.spec
> +%dir %{_datadir}/bash-completion
done

2024-07-01 21:55 UTC, TobiPeterG commented on completion/sdbootutil
> +	_get_comp_words_by_ref -n : cur prev words cword
done

2024-07-08 10:10 UTC, aplanas commented
@TobiPeterG the PR is looking good. Give me some time to test it a bit

2024-07-31 14:42 UTC, TobiPeterG commented
Should I just rebase or do you have any issues with the functionality/code that I should fix with a rebase?

2024-07-31 14:45 UTC, aplanas commented
Yes please, do a rebase. But I need to research a bit more. I found a good reference

2024-09-02 11:11 UTC, aplanas commented on sdbootutil
> +	declare -f set_image_name
ok

2024-09-02 11:14 UTC, aplanas reviewed
I think we can split this PR is two: one for all the bash completions, but another one for the commands refactoring.  This last part is the main source of conflicts right now

2024-09-02 11:14 UTC, aplanas commented on sdbootutil
> +		[set-default-snapshot]=""
I think this has a parameter

2024-09-02 11:14 UTC, aplanas commented on sdbootutil
> +		[show-entry]=""
I think this also has parameters

2024-12-20 22:08 UTC, TobiPeterG commented
Now depends on #172 

I have refactored this PR and split it into multiple commits. Please have a look :)

2024-12-20 22:10 UTC, TobiPeterG commented on sdbootutil
> +		[set-default-snapshot]=""
set-default-snapshot's SNAPSHOT parameter is optional

2024-12-20 22:12 UTC, TobiPeterG commented
To also support snapshots as completion, it would be the easiest to add a new option "--snapshot" that I can check for i nthe completion script. Otherwise it's impossible to know if the user wants to add an option or a snapshot number and I don't want to show both in one list.

2024-12-21 16:33 UTC, TobiPeterG commented
Rebased :)

I added the "_none" function when no completion is useful.

2025-01-16 21:38 UTC, TobiPeterG commented
@aplanas Rebased :)

2025-01-17 12:15 UTC, aplanas requested changes

2025-01-17 12:52 UTC, aplanas requested changes

2025-01-17 12:54 UTC, TobiPeterG commented on sdbootutil
> +	interactive=1
Yes, thanks, will do :)
Missed it, sorry.

2025-01-17 17:50 UTC, TobiPeterG commented on sdbootutil
> +	stty_size
done

2025-01-17 17:50 UTC, TobiPeterG commented on sdbootutil
> +	interactive=1
done

2025-01-17 17:52 UTC, TobiPeterG commented on sdbootutil
> +		[show-entry]=""
Yes, they have the snapshot number as parameter, however, it's optional. So we shouldn't "force" the user to set it.

2025-01-17 17:52 UTC, TobiPeterG commented on sdbootutil
> +		[show-entry]=""
Ah waut, show entry, yes, that is already done :)

2025-01-17 18:18 UTC, aplanas approved these changes
Sorry that this takes so long : (

And thanks!

2025-01-17 18:19 UTC, merged

2025-01-17 18:19 UTC, TobiPeterG commented
> Sorry that this takes so long : (
> 
> And thanks!

All good :)