Make sdbootutil usable with no-snapshot root filesystems
openSUSE/sdbootutil pull request #66
Opened 2024-03-10 19:36 UTC by didopl

As sdboot is in some places a good alternative to grub as it's simpler and lighter, it would be nice if not only btrfs systems with snapper can use this, but also older systems with ext4 or btrfs where snapper is not installed and setup. Currently, sdboot can only be installed on btrfs, snapper systems with this tool. As this tool simplifies a lot when it comes to the install and update process of sdboot it would be convenient to use this on non snapshot systems.
Also from my experience the OS Installer fails to install sdboot when not using snapshots.

Note: This PR is not complete. A lot of functions are still missing and the current changes are so called "quick and dirty" and there might be a way to simplify this.

At current state of this PR, sdbootutil successfully installs sdboot and the kernels.

2024-03-12 10:15 UTC, lnussel commented on sdbootutil
> +no_snapshots=0
maybe call it have_snapshots

2024-03-12 10:34 UTC, lnussel requested changes

2024-03-12 10:34 UTC, lnussel commented on sdbootutil
> +		  --no-snapshots	The running system does not support snapshots
I think this should be auto detected instead

2024-03-12 10:34 UTC, lnussel commented on sdbootutil
> +	fi
would turn into something like
`[ -n "$have_snapshots" ] || return 0`

2024-03-12 10:34 UTC, lnussel commented on sdbootutil
> +	fi
I guess the function could return early without snapshots

2024-03-12 10:34 UTC, lnussel commented on sdbootutil
> +	fi
maybe have the common part in a variable and add the subvol bits only if snapshots are enabled?

2024-03-12 10:34 UTC, lnussel commented on sdbootutil
> +	echo "kerbel_version in remove_kernel: $kernel_version"
left over debugging code

2024-03-12 10:34 UTC, lnussel commented on sdbootutil
> +		local subvol="${subvol_prefix}/.snapshots/${snapshot}/snapshot"
subvol is not actually used in this function

2024-03-12 10:34 UTC, lnussel commented on sdbootutil
>  	local id="$entry_token-$kernel_version-$snapshot.conf"
that would leave a dash if snapshot is empty

2024-03-12 10:34 UTC, lnussel commented on sdbootutil
> +	echo "id: $id"
leftover debug

2024-03-12 10:34 UTC, lnussel commented on sdbootutil
> +	fi
just remove the `:?` in such code I think. It's mostly an assert. Could add an extra function that checks for non-empty in case snapshots are enabled

2024-03-12 10:34 UTC, lnussel commented on sdbootutil
> +			dracut_args=('--force' '--tmpdir' '/var/tmp' '--add-device' "$root_device")
just store this common part first and only add the sysroot option if snapshots are enabled

2024-03-12 10:34 UTC, lnussel commented on sdbootutil
> +	[ -n "$os_release_VERSION" ] || title="$title $os_release_VERSION_ID"
IIRC code related to the title was or will be refactored in a different pr. Just omit for now

2024-03-12 10:34 UTC, lnussel commented on sdbootutil
> +	echo ${!found_kernels[@]}
leftover debug

2024-03-12 10:34 UTC, lnussel commented on sdbootutil
> +						fi
this whole block doesn't make sense without snapshots AFAICT

2024-03-12 10:34 UTC, lnussel commented on sdbootutil
> +	fi
just silently do nothing?

2024-03-12 10:34 UTC, lnussel commented on sdbootutil
> +	fi
doesn't make sense

2024-03-12 10:34 UTC, lnussel commented on sdbootutil
> +fi
this is where we can do the autodetection.
```
if [ "$(stat -f -c %T /)" = "btrfs" ] && [ -d /.snapshots ]; then
  have_snapshots=1
  root_subvol=...
```

2024-03-12 11:55 UTC, didopl commented on sdbootutil
> +no_snapshots=0
Since snapshotting is getting more widely used, I would this maybe have_no_snapshots. This also requires less code changings.

2024-03-12 11:56 UTC, didopl commented on sdbootutil
> +		  --no-snapshots	The running system does not support snapshots
Agree.

2024-03-12 11:57 UTC, didopl commented on sdbootutil
> +	fi
I'm not a big fan of doing things completely silent, but a warning might be better in this case.

2024-03-12 11:59 UTC, didopl commented on sdbootutil
> +	fi
For me, I was unable to choose which entry to boot, since it didn't add a timeout in loader.conf

2024-03-12 12:04 UTC, didopl commented on sdbootutil
> +		local subvol="${subvol_prefix}/.snapshots/${snapshot}/snapshot"
Yep.

2024-03-12 12:55 UTC, lnussel commented on sdbootutil
> +	fi
that's how bootctl install behaves by default so we keep that. it's not related to snapshots

2024-03-12 13:10 UTC, didopl commented on sdbootutil
> +	fi
I'm not familiar at all with sed. Where does sed store the output? Is it written to a file as it seems this line sets the cmdline for the kernel or is it stored i an variable which is written to file then? I would appreciate some help here.

2024-03-12 13:12 UTC, didopl commented on sdbootutil
> +	fi
So just leave out the `:?` and no if/test-statement?

2024-03-12 13:31 UTC, didopl commented on sdbootutil
> +	fi
Yes.

2024-03-12 13:35 UTC, didopl commented on sdbootutil
> +	fi
So when using have_no_snapshots instead, this would look like this:
`[ -n "$have_no_snapshots" ] && return 0`

2024-03-12 13:46 UTC, didopl commented on sdbootutil
> +						fi
So just add `[ -n "$have_no_snapshots" ] && break` before?

2024-03-12 13:58 UTC, didopl commented on sdbootutil
> +fi
So to make it work with have_no_snapshots:
  
```
if ! { [ "$(stat -f -c %T /)" = "btrfs" ] && [ -d /.snapshots ]; }; then
    have_no_snapshots=1  
    root_subvol=""  
    sub_vol_prefix=""  
else...
```

2024-03-12 19:24 UTC, didopl commented on sdbootutil
> +	fi
Ok, interesting. I will delete this.

2024-03-12 19:29 UTC, didopl commented on sdbootutil
> +	fi
Added.

2024-03-12 19:31 UTC, didopl commented on sdbootutil
> +			dracut_args=('--force' '--tmpdir' '/var/tmp' '--add-device' "$root_device")
Should be added now

2024-03-12 19:32 UTC, didopl commented on sdbootutil
> +	fi
Is removed.

2024-03-12 19:33 UTC, didopl commented on sdbootutil
>  	local id="$entry_token-$kernel_version-$snapshot.conf"
Removed.

2024-03-12 19:35 UTC, didopl commented on sdbootutil
> +	echo "kerbel_version in remove_kernel: $kernel_version"
Removed.

2024-03-12 19:36 UTC, didopl commented on sdbootutil
> +	fi
Should `return 0` now.

2024-03-12 19:37 UTC, didopl commented on sdbootutil
> +		  --no-snapshots	The running system does not support snapshots
Auto detection works from my tests.

2024-03-12 19:38 UTC, didopl commented on sdbootutil
> +	echo ${!found_kernels[@]}
Removed.

2024-03-12 19:46 UTC, didopl commented on sdbootutil
> +	echo "id: $id"
Removed.

2024-03-13 20:21 UTC, didopl commented on sdbootutil
> +	fi
I just do it in two commands now.

2024-03-13 20:22 UTC, didopl commented on sdbootutil
> +fi
I tested with a snapshot system and it installed correctly, so auto-detection should be fine.

2024-03-14 09:17 UTC, lnussel commented on sdbootutil
> +no_snapshots=0
the point of have_snapshots would be that we could potentially define other values in the future to support a different form of snapshots, not just the snapper way.

2024-03-14 09:34 UTC, lnussel requested changes

2024-03-14 09:34 UTC, lnussel commented on sdbootutil
> +	fi
yes

2024-03-14 09:34 UTC, lnussel commented on sdbootutil
> +	test -e "$src" || err "Can't find $src"
Wonder how test creeped in here. Should be `[]`. Anyway the reordering here doesn't seem to be necessary?

2024-03-14 09:34 UTC, lnussel commented on sdbootutil
> +	snapshot="${snapshot%/snapshot}"
broken rebase? This should not exist

2024-03-14 09:34 UTC, lnussel commented on sdbootutil
> +	# [ -n "$os_release_VERSION" ] || title="$title $os_release_VERSION_ID"
unrelated, again probably result of rebase fallout

2024-03-14 09:34 UTC, lnussel commented on sdbootutil
> +		[ -n "$have_no_snapshots" ] && loader_entry="$boot_root/loader/entries/$entry_token-$kernel_version.conf"
`"...${snapshot:+-$snapshot}.conf"`

2024-03-14 09:34 UTC, lnussel commented on sdbootutil
> +
skip parsing the options line one line above?

2024-03-14 09:34 UTC, lnussel commented on sdbootutil
> +		local prefix=""
just move the declaration out and only set prefix if snapshots are enabled

2024-03-14 09:34 UTC, lnussel commented on sdbootutil
> +	[ -e "$boot_root/loader/loader.conf" ] || echo -e "#timeout 3\n#console-mode keep\n" > "$boot_root/loader/loader.conf"
not needed

2024-03-14 09:34 UTC, lnussel commented on sdbootutil
> +fi
no else needed here with `have_snapshots`

2024-03-14 20:01 UTC, didopl commented on sdbootutil
> +no_snapshots=0
That makes totally sense of course. So I will try to do it with have_snapshots.

2024-03-15 12:50 UTC, didopl commented on sdbootutil
> +	snapshot="${snapshot%/snapshot}"
Removed.

2024-03-15 12:51 UTC, didopl commented on sdbootutil
> +		local prefix=""
Added.

2024-03-15 12:51 UTC, didopl commented on sdbootutil
> +	[ -e "$boot_root/loader/loader.conf" ] || echo -e "#timeout 3\n#console-mode keep\n" > "$boot_root/loader/loader.conf"
Removed.

2024-03-15 12:52 UTC, didopl commented on sdbootutil
> +	fi
Using have_snapshots now.

2024-03-15 13:01 UTC, didopl commented on sdbootutil
> +	[ -e "$boot_root/loader/loader.conf" ] || echo -e "#timeout 3\n#console-mode keep\n" > "$boot_root/loader/loader.conf"
Removed.

2024-03-18 12:32 UTC, lnussel requested changes
please use shellcheck, that would eliminate some trivial mistakes

2024-03-18 12:32 UTC, lnussel commented on sdbootutil
> +[ -n "$root_subvol" ] || [ -z "$have_snashots" ] || err "Can't determine root subvolume"
typo

2024-03-18 12:32 UTC, lnussel commented on sdbootutil
> +sub_vol_prefix=""
typo

2024-03-18 12:32 UTC, lnussel commented on sdbootutil
> +	[ -n "$have_snapshots" ] || log_info "System does not support snaphsots." && exit 0
`[ -n "$have_snapshots" ] || { log_info ...; return 0; }`

Same in several other places wherever this pattern appears

2024-03-18 12:32 UTC, lnussel commented on sdbootutil
> +	sed -e "s,\<rootflags=subvol=[^ ]*,rootflags=subvol=$subvol,;tx; s,\$, rootflags=subvol=$subvol,;:x"
please rebase. You can now move the sed arguments into an array and add the subvol part on demand

2024-03-18 12:32 UTC, lnussel commented on sdbootutil
> +	[ -n "$have_snapshots" ] && snapshot="${snapshot%/*}"
no longer needed

2024-03-18 12:32 UTC, lnussel commented on sdbootutil
> +	local subvol="${2}"
would look better without `{}`

2024-03-18 12:32 UTC, lnussel commented on sdbootutil
> +	[ -n "$have_snapshots" ] && subvol="${subvol_prefix}/.snapshots/${snapshot}/snapshot"
`[ -z "$have_snapshots" ] || subvol=...`

2024-03-18 12:32 UTC, lnussel commented on sdbootutil
> +	# [ -n "$have_snapshots" ] || snapshot=""
not needed

2024-03-18 12:32 UTC, lnussel commented on sdbootutil
> +		echo $boot_options
debug

2024-03-18 12:32 UTC, lnussel commented on sdbootutil
> +	[ -n "$have_snapshots" ] && subvol="${subvol_prefix}/.snapshots/${1:?}/snapshot"
you've dropped the snapshot var

2024-03-18 12:32 UTC, lnussel commented on sdbootutil
> +
extra whitespace

2024-03-18 18:33 UTC, didopl commented on sdbootutil
> +	local subvol="${2}"
Changed in some other places too, not sure if necessary, but works.

2024-03-18 18:33 UTC, didopl commented on sdbootutil
> +	[ -n "$have_snapshots" ] && snapshot="${snapshot%/*}"
Removed.

2024-03-18 18:33 UTC, didopl commented on sdbootutil
> +	sed -e "s,\<rootflags=subvol=[^ ]*,rootflags=subvol=$subvol,;tx; s,\$, rootflags=subvol=$subvol,;:x"
Works now from my tests.

2024-03-18 18:33 UTC, didopl commented on sdbootutil
> +	[ -n "$have_snapshots" ] && subvol="${subvol_prefix}/.snapshots/${snapshot}/snapshot"
Changed.

2024-03-18 18:33 UTC, didopl commented on sdbootutil
> +	# [ -n "$have_snapshots" ] || snapshot=""
Removed.

2024-03-18 18:33 UTC, didopl commented on sdbootutil
> +		echo $boot_options
Removed.

2024-03-18 18:34 UTC, didopl commented on sdbootutil
> +	[ -n "$have_snapshots" ] && subvol="${subvol_prefix}/.snapshots/${1:?}/snapshot"
snapshot added again.

2024-03-18 18:34 UTC, didopl commented on sdbootutil
> +
Removed.

2024-03-18 18:36 UTC, didopl commented on sdbootutil
> +	fi
See below.

2024-03-18 18:38 UTC, didopl commented on sdbootutil
> +		[ -n "$have_no_snapshots" ] && loader_entry="$boot_root/loader/entries/$entry_token-$kernel_version.conf"
Should be added.

2024-03-18 18:38 UTC, didopl commented on sdbootutil
> +
Line is moved.

2024-03-18 18:39 UTC, didopl commented on sdbootutil
> +	test -e "$src" || err "Can't find $src"
Replaced with [].

2024-03-18 18:39 UTC, didopl commented on sdbootutil
> +[ -n "$root_subvol" ] || [ -z "$have_snashots" ] || err "Can't determine root subvolume"
Fixed.

2024-03-18 18:39 UTC, didopl commented on sdbootutil
> +sub_vol_prefix=""
Fixed.

2024-03-18 18:40 UTC, didopl commented on sdbootutil
> +	[ -n "$have_snapshots" ] || log_info "System does not support snaphsots." && exit 0
Replaced.

2024-03-19 07:10 UTC, lnussel requested changes
those two minor things otherwise looks quite good

Please rebase and squash on main to have a single commit.

2024-03-19 07:10 UTC, lnussel commented on sdbootutil
> +	[ -z "$have_snapshots" ] || subvol="${subvol_prefix}/.snapshots/${1:?}/snapshot"
does not set snapshot anymore now

2024-03-19 20:52 UTC, didopl commented on sdbootutil
> +	[ -z "$have_snapshots" ] || local snapshot="${1:?}"
Removed.

2024-03-20 10:12 UTC, lnussel commented
`git rebase -i` is quite nice as it allows you to reorder, squash and edit commits. Anyway good to go code wise! Use `git commit --amend --reset-author` to produce a descriptive commit message. You may also want to configure your git settings before to have a proper name and email address (`man git-config`).

2024-03-25 12:43 UTC, lnussel approved these changes

2024-03-25 12:43 UTC, merged