Add initial GRUB2 support
openSUSE/sdbootutil pull request #67
Opened 2024-03-11 11:50 UTC by aplanas

2024-03-11 16:41 UTC, lnussel requested changes

2024-03-11 16:41 UTC, lnussel commented on sdbootutil
> +	grub2="$(find_grub2)"
pass snapshot as argument? That way it would be possible to change the bootloader based on target snapshot

2024-03-11 16:41 UTC, lnussel commented on sdbootutil
> +	install -p -m 0644 "$src" "$dst" || return "$?"
does this work? FAT has lower precision time stamps IIIRC

2024-03-11 16:41 UTC, lnussel commented on sdbootutil
> +	local prefix="/.snapshots/${1-$root_snapshot}/snapshot"
would do the fallback to root_snapshot in the caller. I think that's the way it's done in other functions

2024-03-11 16:41 UTC, lnussel commented on sdbootutil
> +		rsync -aL --delete --safe-links "$boot_root/../grub2" "$boot_root"
We need to sync from the original source in /usr here. /boot might be the XBOOTLDR partition in the future end esp not mounted in /boot/efi

Does grub.efi actually need all those files anyway? thought it was modules from a time before secure boot when grub had to have all modules built in?

2024-03-11 17:06 UTC, aplanas commented on sdbootutil
> +	grub2="$(find_grub2)"
yes, done

2024-03-11 17:13 UTC, aplanas commented on sdbootutil
> +		rsync -aL --delete --safe-links "$boot_root/../grub2" "$boot_root"
The theme and fonts are there (and in /usr/share) but also the grub.cfg.

2024-03-11 18:05 UTC, aplanas commented on sdbootutil
> +		rsync -aL --delete --safe-links "$boot_root/../grub2" "$boot_root"
removed for now, I am trying a different approach

2024-03-11 18:07 UTC, aplanas commented on sdbootutil
> +	local prefix="/.snapshots/${1-$root_snapshot}/snapshot"
uhm no, check find_sdboot: https://github.com/openSUSE/sdbootutil/blob/main/sdbootutil#L954

2024-03-12 10:14 UTC, lnussel commented
We probably need to bikeshed over the dialog title a bit otherwise looks fine

2024-03-12 10:14 UTC, lnussel approved these changes

2024-03-12 10:37 UTC, aplanas commented
I will keep it a bit longer in draft mode, as the last commit can change a bit: I want to generate the grub.cfg in the installation verb

2024-03-12 15:43 UTC, aplanas commented
Ready for full review. The last commit add a default grub.cfg and sync one single module (bli.mod) that is needed to the EFI vars

2024-03-14 09:42 UTC, merged