Remove old kernels when no space is available
openSUSE/sdbootutil pull request #70
Opened 2024-03-12 13:34 UTC by TobiPeterG

This will clean up old kernels to free space on the ESP when a new kernel should be installed. Only kernels that are not installed in the to be installed snapshot and root snapshot (current snaphsot) might be removed

This should be a solution to https://github.com/openSUSE/sdbootutil/issues/26

Tested this on Tumbleweed

2024-03-12 13:34 UTC, TobiPeterG commented
If no kernel can be removed, the install command fails

2024-03-14 09:54 UTC, lnussel requested changes
Two remarks

If we do this I think we should make two passes over the to-be installed files instead. Ie first calculate the space they'd need. Then call a cleanup function, then try installing again if there's enough space.

The mechanism needs to be based on entry files rather than kernels though. We know the list of entries and it is sorted IIRC so we can purge the oldest by means of bootctl remove. bootctl takes care of reference counting and removing all related files, including eg device trees. We should not delete kernels or entries ourselves.

2024-03-22 11:16 UTC, TobiPeterG commented on sdbootutil
> +	src_size_kb=$(du -k "$src" | cut -f1)
done :)

2024-03-22 11:18 UTC, TobiPeterG commented on sdbootutil
> +	mkdir -p "$(dirname "$dst")" 2>/dev/null || :
done :)

2024-03-22 11:18 UTC, TobiPeterG commented on sdbootutil
> +	while [[ "$available_space_kb" -lt "$src_size_kb" ]]; do
done

2024-03-22 11:22 UTC, TobiPeterG commented on sdbootutil
> +			available_space_kb=$(df -k "$(dirname "$dst")" | awk 'NR==2 {print $4}')
done, however, this needs explicit conversion to kb as findmnt returns size in bytes

2024-03-22 11:26 UTC, TobiPeterG commented
> Two remarks
> 
> If we do this I think we should make two passes over the to-be installed files instead. Ie first calculate the space they'd need. Then call a cleanup function, then try installing again if there's enough space.
> 
> The mechanism needs to be based on entry files rather than kernels though. We know the list of entries and it is sorted IIRC so we can purge the oldest by means of bootctl remove. bootctl takes care of reference counting and removing all related files, including eg device trees. We should not delete kernels or entries ourselves.

I changed the logic to unlinki the entries instead of manually removing files. :)

2024-03-25 17:33 UTC, lnussel requested changes
As I said, two passes would be better. Ie don't hook into install_with_rollback

Also needs rebase now

2024-03-25 17:33 UTC, lnussel commented on sdbootutil
> +	src_size_kb=$(du -k "$src" | { read size _; echo "$size"; })
`read -r src_size  _p < <(du -k "$src")`

2024-03-25 17:33 UTC, lnussel commented on sdbootutil
> +			available_space_kb=$(df -k "${dst%/*}" | awk 'NR==2 {print $4}')
read

2024-03-25 17:33 UTC, lnussel commented on sdbootutil
> +	local bootable_kernels=($(ls "$efi_kernel_dir" | sort -V))
you can just get the entries from bootctl. They are sorted so oldest should be last?

2024-04-07 19:45 UTC, TobiPeterG commented on sdbootutil
> +			available_space_kb=$(df -k "${dst%/*}" | awk 'NR==2 {print $4}')
done

2024-04-07 19:45 UTC, TobiPeterG commented on sdbootutil
> +	src_size_kb=$(du -k "$src" | { read size _; echo "$size"; })
done

2024-04-07 20:21 UTC, TobiPeterG commented on sdbootutil
> +	local bootable_kernels=($(ls "$efi_kernel_dir" | sort -V))
done

2024-04-07 20:25 UTC, TobiPeterG commented
So, I think I made the requested changes. Please test it, as I'm currently not home and don't have a testing environment.

I noticed that e.g. in the install_kernel the version is set to snapshot@kernel_version, even though $snapshot might not be set, I guess that would only leave @kernel_version, is that wanted?

2024-04-09 19:34 UTC, TobiPeterG commented
> So, I think I made the requested changes. Please test it, as I'm currently not home and don't have a testing environment.
> 
> I noticed that e.g. in the install_kernel the version is set to snapshot@kernel_version, even though $snapshot might not be set, I guess that would only leave @kernel_version, is that wanted?

Could test it today, should work now :)

2024-04-27 13:06 UTC, TobiPeterG commented
@lnussel did you have a chance to review it yet? :)

2024-04-30 08:30 UTC, lnussel commented
it's still trying to free space several times. IMO a better way would be to either

- calculate the required space beforehand and free if needed. We then even know how much actually was freed to check whether install fits without trying.
- or alternatively free space when install failed but then only do it once and retry once. ie not on every initrd copy

2024-05-23 23:30 UTC, TobiPeterG commented
> it's still trying to free space several times. IMO a better way would be to either
> 
> * calculate the required space beforehand and free if needed. We then even know how much actually was freed to check whether install fits without trying.
> * or alternatively free space when install failed but then only do it once and retry once. ie not on every initrd copy

I tried to rework it, I hope this is now what you are looking for :)
Every file that needs to be installed is added to an array and it's saved how much storage will be required for all of these files. We then try to make space for them, then we try to install them.
I also reworked the installation process of files a bit, I hope I didn't miss any important conditional. :)

2024-06-06 16:47 UTC, aplanas commented
@TobiPeterG I think that this feature is really important and I want have it in sdbootutil.  I was reviewing the code but it confuses me.

Sadly @lnussel will not review this PR, as he left the company to work on different projects. But if I understand him correctly the solution proposes is much more simple:

1) Around [here](https://github.com/openSUSE/sdbootutil/blob/main/sdbootutil#L614) in `install_kernel` the kernel and all the initrds are in place. The kernel in `$src` and the initrds in `$tmpdir/initrd-*`.  Note that the multiple initrd is not really working, depends on a project, mkmoduleinitrd, that is still not working.  But lets assume that there are multiple initrd in place for now

2) In this moment we know the expected size. We can add the kernel and the initrds size, and compare with the free space in the ESP.

3) If there is no free space, we need to list all the boot entries. For that we call `update_entries` to generate the entry file JSON file, and we iterate it to get the `id` (you are doing this already in your code)

4) With this list, in reverse order (I think that the filter to ID and reversing the list can be done in a single `jq`) we do `run_command_output bootctl unlink "$id"` for all the entries, except three: the last working snapshot, the current and the new one. See this: https://github.com/openSUSE/sdbootutil/blob/main/sdbootutil#L1405

In that regard `install_kernel` should not refactored, and there is no need to any global variable or keeping list of files to install. Just a some code in the line 614 (maybe a call to a function) to the sum of the kernel and initrds file and the bootctl unlink until there is free space or the list if IDs is exhausted.  This list can be generated using the complementary of the function from line 1405.

Do you want to try? Should I try and you do the review?

2024-06-11 23:29 UTC, TobiPeterG commented
> @TobiPeterG I think that this feature is really important and I want have it in sdbootutil.  I was reviewing the code but it confuses me.
> 
> Sadly @lnussel will not review this PR, as he left the company to work on different projects. But if I understand him correctly the solution proposes is much more simple:
> 
> 1) Around [here](https://github.com/openSUSE/sdbootutil/blob/main/sdbootutil#L614) in `install_kernel` the kernel and all the initrds are in place. The kernel in `$src` and the initrds in `$tmpdir/initrd-*`.  Note that the multiple initrd is not really working, depends on a project, mkmoduleinitrd, that is still not working.  But lets assume that there are multiple initrd in place for now
> 
> 2) In this moment we know the expected size. We can add the kernel and the initrds size, and compare with the free space in the ESP.
> 
> 3) If there is no free space, we need to list all the boot entries. For that we call `update_entries` to generate the entry file JSON file, and we iterate it to get the `id` (you are doing this already in your code)
> 
> 4) With this list, in reverse order (I think that the filter to ID and reversing the list can be done in a single `jq`) we do `run_command_output bootctl unlink "$id"` for all the entries, except three: the last working snapshot, the current and the new one. See this: https://github.com/openSUSE/sdbootutil/blob/main/sdbootutil#L1405
> 
> In that regard `install_kernel` should not refactored, and there is no need to any global variable or keeping list of files to install. Just a some code in the line 614 (maybe a call to a function) to the sum of the kernel and initrds file and the bootctl unlink until there is free space or the list if IDs is exhausted.  This list can be generated using the complementary of the function from line 1405.
> 
> Do you want to try? Should I try and you do the review? 


Hey, thank you very much for your message. :)
I would be happy to write the code, however, my studies, job and preparation for the openSUSEcon are currently keeping me busy (I'm unfortunately not paid for my work for SUSE ( yet ;) ), so I can't tell when I'll have the time (though I hope soon™).
If you want to write the code, I'd also be happy to review it (after all, in the end, what matters is that the feature works) :)

2024-06-19 10:19 UTC, TobiPeterG commented
done in #99

2024-06-19 10:19 UTC, closed without merging