Add new options to sdbootutil
openSUSE/sdbootutil pull request #90
Opened 2024-05-09 13:34 UTC by aplanas

The idea is to have a way to detect the default boot entry without reading the `LoaderEntryDefault` EFI var (`--default-entry`) and select the current `initrd` (`--fields=initrd`). This can be used in other scripts (`--no-colors`) that need to find those attributes

2024-05-13 08:41 UTC, lnussel commented
what's your use case? You could just call bootctl list yourself...

2024-05-13 08:57 UTC, aplanas commented
Doing `bootctl list --json=short` and filter the default entry and get the fields with `jq` is definitively an option, but I would not do that in the weak-modules2 from suse-module-tools. The two options that I considered was:

1) make this a feature of sdbootutil (this one), as wm2 will use it in any case
2) make wm2 to read the EFI variable to fetch the default boot entry, and read the file to separate the k/v to filter the fields (initrd in this case)

2024-05-13 12:39 UTC, lnussel commented
as agreed offline, we will introduce some `sdbootutil show-entry` command that receives a kernel version (optional snapshot number) to show the entry for a given kernel or selected fields of that entry.

2024-05-13 14:13 UTC, aplanas commented
@lnussel I added the `show-entry` command

2024-05-13 15:39 UTC, lnussel requested changes

2024-05-13 15:39 UTC, lnussel commented on sdbootutil
> +	echo -e "$fields"
Use an array instead?

2024-05-13 15:39 UTC, lnussel commented on sdbootutil
> +			[ -z "$arg_no_colors" ] || echo -e "  ${errors[*]}" >&2
would look better if we used something like color_red="\e[31m" and leave it empty if no colors are requested

2024-05-13 15:39 UTC, lnussel commented on sdbootutil
> +		--no-colors) arg_no_colors=1; shift ;;
systemd uses $SYSTEMD_COLORS instead of a separate command line switch. Maybe just use that too?

2024-05-13 15:40 UTC, lnussel requested changes

2024-05-13 15:40 UTC, lnussel commented on sdbootutil
> +		  --fields		Comma separated list of fields
https://uapi-group.org/specifications/specs/boot_loader_specification/ calls them keys. `--entry-keys`, `--show-entry-keys`?

2024-05-13 16:15 UTC, aplanas commented on sdbootutil
> +			[ -z "$arg_no_colors" ] || echo -e "  ${errors[*]}" >&2
I do not think so, the ANSI color are two elements: a prefix and a suffix (`\e[m`).  I would need to introduce a new var (`color_end`) that can conditionally be empty. IMO it is clear this way

2024-05-13 16:15 UTC, aplanas commented on sdbootutil
> +	echo -e "$fields"
done

2024-05-13 16:21 UTC, aplanas commented on sdbootutil
> +		--no-colors) arg_no_colors=1; shift ;;
done

2024-05-13 16:23 UTC, aplanas commented on sdbootutil
> +		  --fields		Comma separated list of fields
done

2024-05-14 06:55 UTC, lnussel commented on sdbootutil
> +			[ -z "$arg_no_colors" ] || echo -e "  ${errors[*]}" >&2
exactly, a marker for end also. that avoid duplicating the actual command

2024-05-14 06:58 UTC, lnussel requested changes

2024-05-14 06:58 UTC, lnussel commented on sdbootutil
> +		SDB_NO_COLORS			Disable colored output
I meant literall SYSTEMD_COLORS. SDB_ADD_INITIAL_CMDLINE is rather internal right, wouldn't even document that

2024-05-14 06:58 UTC, lnussel commented on sdbootutil
> +	printf "%b\n" "${output[@]}"
Sorry for not realizing this earlier but this can be turned into a simple echo in the loop. The result isn't used anymore afterwards

2024-05-14 07:56 UTC, aplanas commented on sdbootutil
> +		SDB_NO_COLORS			Disable colored output
done

2024-05-14 07:56 UTC, aplanas commented on sdbootutil
> +	printf "%b\n" "${output[@]}"
done

2024-05-14 12:09 UTC, lnussel approved these changes

2024-05-14 12:11 UTC, merged