Allocate free space in /boot
openSUSE/sdbootutil pull request #99
Opened 2024-06-14 13:37 UTC by aplanas

Alternative for https://github.com/openSUSE/sdbootutil/pull/70

2024-06-14 13:37 UTC, aplanas commented
cc @TobiPeterG

2024-06-16 12:11 UTC, TobiPeterG commented
Hey there,
I tested the code a bit, I don't know exactly what you want it to do, but it doesn't remove the oldest kernel, but it seems to remove the entries of the oldest snapshot it finds. Also, it doesn't respect the snapshot I want to install my kernels from. I had the following setup: 
10.9.1-1-default  14.9.1-1-default  6.6.6-1-default
11.9.1-1-default  15.9.1-1-default  6.9.1-1-default
12.9.1-1-default  5.9.1-1-default   7.9.1-1-default
13.9.1-1-default  6.5.4-1-default   8.9.1-1-default
These kernels are in the esp, each with a entry (snapshot number 300)
When I want to install a kernel for the current snapshot (82), it correctly doesn't remove entries from that snapshot.
However, it doesn't remove kernel 5.9, but the entries of snapshot 214 and 217:
```
sudo sdbootutil -v add-all-kernels
found kernel 6.6.6-1-default = 5693bb90f9b3f5c84d68e60f12a412746a13e7fb
found kernel 6.9.1-1-default = 6b13316fa0178df1fd6898c8f96f96ab9ecbbbe1
installing 6.9.1-1-default
generating new initrd
loading 123 failed
loading 124 failed
loading 125 failed
loading 126 failed
loading 215 failed
loading 216 failed
loading 219 failed
loading 220 failed
loading 222 failed
loading 223 failed
Removing boot entry opensuse-tumbleweed-6.6.6-1-default-214.conf
Removed "/boot/efi/opensuse-tumbleweed/6.6.6-1-default/initrd-6dcb8bc8e4f6b29cb6a2cacfd05e1b75411eaaef"
Removed /boot/efi/loader/entries/opensuse-tumbleweed-6.6.6-1-default-214.conf
installed /boot/efi/opensuse-tumbleweed/6.9.1-1-default/linux-6b13316fa0178df1fd6898c8f96f96ab9ecbbbe1
installed /boot/efi/opensuse-tumbleweed/6.9.1-1-default/initrd-4d7dfdd5bb026c5b74d48ecb2bd3935dd4cdd07a
installed /boot/efi/loader/entries/opensuse-tumbleweed-6.9.1-1-default-82.conf
installing 6.6.6-1-default
generating new initrd
Removing boot entry opensuse-tumbleweed-6.6.6-1-default-217.conf
Removed "/boot/efi/opensuse-tumbleweed/6.6.6-1-default/initrd-2ecde857d422c83b2a1b22a22edde74620dc7f19"
Removed /boot/efi/loader/entries/opensuse-tumbleweed-6.6.6-1-default-217.conf
reusing /boot/efi/opensuse-tumbleweed/6.6.6-1-default/linux-5693bb90f9b3f5c84d68e60f12a412746a13e7fb
installed /boot/efi/opensuse-tumbleweed/6.6.6-1-default/initrd-339d0bc20cf786b165c5979859cc09656cd7b881
installed /boot/efi/loader/entries/opensuse-tumbleweed-6.6.6-1-default-82.conf
```

When I install a kernel from snapshot 214 now, I would expect sdbootutil to not remove entries from the current snapshot and the snapshot I want to add kernels from. However, the following happens when I want to install kernel from snapshot 214:
```
sudo sdbootutil -v add-all-kernels 214
found kernel 6.4.12-1-default = df1cfa4de2484f72065edd8618d075ff6dc3a7fd
found kernel 6.5.4-1-default = d188a529bfb1f986f9bfbd5ba124683bffa73e41
found kernel 6.6.6-1-default = 5693bb90f9b3f5c84d68e60f12a412746a13e7fb
installing 6.4.12-1-default
generating new initrd
gzip: /var/tmp/dracut.TPEpe4/initramfs/.snapshots/214/snapshot/usr/share/kbd/keymaps/xkb/de-nodeadkeys.map.gz: No such file or directory
loading 123 failed
loading 124 failed
loading 125 failed
loading 126 failed
loading 215 failed
loading 216 failed
loading 219 failed
loading 220 failed
loading 222 failed
loading 223 failed
Removing boot entry opensuse-tumbleweed-6.6.6-1-default-218.conf
Removed "/boot/efi/opensuse-tumbleweed/6.6.6-1-default/initrd-4ac962a6dc6a6e08e374d6f50af6730e673767e6"
Removed /boot/efi/loader/entries/opensuse-tumbleweed-6.6.6-1-default-218.conf
loading 123 failed
loading 124 failed
loading 125 failed
loading 126 failed
loading 215 failed
loading 216 failed
loading 219 failed
loading 220 failed
loading 222 failed
loading 223 failed
installed /boot/efi/opensuse-tumbleweed/6.4.12-1-default/linux-df1cfa4de2484f72065edd8618d075ff6dc3a7fd
installed /boot/efi/opensuse-tumbleweed/6.4.12-1-default/initrd-9a53a072a95c098aff9390c57f6118adfecbc69e
installed /boot/efi/loader/entries/opensuse-tumbleweed-6.4.12-1-default-214.conf
installing 6.5.4-1-default
generating new initrd
gzip: /var/tmp/dracut.v9IfbS/initramfs/.snapshots/214/snapshot/usr/share/kbd/keymaps/xkb/de-nodeadkeys.map.gz: No such file or directory
Removing boot entry opensuse-tumbleweed-6.4.12-1-default-214.conf
Removed "/boot/efi/opensuse-tumbleweed/6.4.12-1-default/linux-df1cfa4de2484f72065edd8618d075ff6dc3a7fd"
Removed "/boot/efi/opensuse-tumbleweed/6.4.12-1-default/initrd-9a53a072a95c098aff9390c57f6118adfecbc69e"
Removed /boot/efi/loader/entries/opensuse-tumbleweed-6.4.12-1-default-214.conf
loading 123 failed
loading 124 failed
loading 125 failed
loading 126 failed
loading 215 failed
loading 216 failed
loading 219 failed
loading 220 failed
loading 222 failed
loading 223 failed
installed /boot/efi/opensuse-tumbleweed/6.5.4-1-default/linux-d188a529bfb1f986f9bfbd5ba124683bffa73e41
installed /boot/efi/opensuse-tumbleweed/6.5.4-1-default/initrd-1cd1b8faf92e17debf037c98bd84fec63f8145d0
installed /boot/efi/loader/entries/opensuse-tumbleweed-6.5.4-1-default-214.conf
installing 6.6.6-1-default
found existing initrd /opensuse-tumbleweed/6.6.6-1-default/initrd-339d0bc20cf786b165c5979859cc09656cd7b881
Removing boot entry opensuse-tumbleweed-6.5.4-1-default-214.conf
Removed "/boot/efi/opensuse-tumbleweed/6.5.4-1-default/linux-d188a529bfb1f986f9bfbd5ba124683bffa73e41"
Removed "/boot/efi/opensuse-tumbleweed/6.5.4-1-default/initrd-1cd1b8faf92e17debf037c98bd84fec63f8145d0"
Removed /boot/efi/loader/entries/opensuse-tumbleweed-6.5.4-1-default-214.conf
loading 123 failed
loading 124 failed
loading 125 failed
loading 126 failed
loading 215 failed
loading 216 failed
loading 219 failed
loading 220 failed
loading 222 failed
loading 223 failed
reusing /boot/efi/opensuse-tumbleweed/6.6.6-1-default/linux-5693bb90f9b3f5c84d68e60f12a412746a13e7fb
installed /boot/efi/loader/entries/opensuse-tumbleweed-6.6.6-1-default-214.conf
```

It just removes the just added entries and kernels again. This is not what I as a user would expect to happen. I would like sdbootutil to either remove the oldest kernels or remove the entries from the oldest snapshots, that are not my root snapshot and the snapshot I want to install kernels from.

2024-06-16 13:25 UTC, aplanas commented
> Hey there, I tested the code a bit, I don't know exactly what you want it to do

Basically free some space in the ESP when a new entry is created.

>, but it doesn't remove the oldest kernel, but it seems to remove the entries of the oldest snapshot it finds. 

That is right. As commented initially here: https://github.com/openSUSE/sdbootutil/pull/70#pullrequestreview-1936180460 and later here https://github.com/openSUSE/sdbootutil/pull/70#issuecomment-2152974299 maybe is better to remove full entries (.conf, kernel, initrd) instead of only the kernel (keeping a broken entry in the ESP).

As `bootctl` keeps a reference counting of used kernel and initrds, a `bootctil unlink` will remove the kernel only if it is not referenced by any other entry.  This avoid from us to do the same in the code, with the advantage that we are sure that all the remaining entries are still valid.

It is not better that way?

> Also, it doesn't respect the snapshot I want to install my kernels from.

OK, that seems a bug, I will check

> I had the following setup: 10.9.1-1-default 14.9.1-1-default 6.6.6-1-default 11.9.1-1-default 15.9.1-1-default 6.9.1-1-default 12.9.1-1-default 5.9.1-1-default 7.9.1-1-default 13.9.1-1-default 6.5.4-1-default 8.9.1-1-default 

Uhmm I am confused. 10.9.1, 14.9.1 ... you manually put this version in the boot entry?

> These kernels are in the esp, each with a entry (snapshot number 300) When I want to install a kernel for the current snapshot (82), it correctly doesn't remove entries from that snapshot. However, it doesn't remove kernel 5.9, but the entries of snapshot 214 and 217:

The removal of the entries are in date order. So the global oldest is removed first. If will iterate the list in this order, avoiding to remove the ones that we generate a prediction for.

What output do you have for `bootctl list`, are they removed in the order showed there?

> When I install a kernel from snapshot 214 now, I would expect sdbootutil to not remove entries from the current snapshot and the snapshot I want to add kernels from. However, the following happens when I want to install kernel from snapshot 214:

Uhm maybe I need to add a sort_by the date.

> It just removes the just added entries and kernels again. This is not what I as a user would expect to happen. I would like sdbootutil to either remove the oldest kernels or remove the entries from the oldest snapshots, that are not my root snapshot and the snapshot I want to install kernels from.

It kept the default, active and last working on MicroOS. Maybe indeed there is a problem in the selection

2024-06-16 13:41 UTC, TobiPeterG commented
> > Hey there, I tested the code a bit, I don't know exactly what you want it to do
> 
> Basically free some space in the ESP when a new entry is created.
>
> >, but it doesn't remove the oldest kernel, but it seems to remove the entries of the oldest snapshot it finds. 
> 
> That is right. As commented initially here: https://github.com/openSUSE/sdbootutil/pull/70#pullrequestreview-1936180460 and later here https://github.com/openSUSE/sdbootutil/pull/70#issuecomment-2152974299 maybe is better to remove full entries (.conf, kernel, initrd) instead of only the kernel (keeping a broken entry in the ESP).
> 

I always removed the entry with the kernel, I just did it manually at first :)


> As `bootctl` keeps a reference counting of used kernel and initrds, a `bootctil unlink` will remove the kernel only if it is not referenced by any other entry.  This avoid from us to do the same in the code, with the advantage that we are sure that all the remaining entries are still valid.
> 
> It is not better that way?
> 

Of course it is. I would just like the removal to behave as expected by a user (if you have another idea how it should work, that's also valid, but that's what my first question about what it should do was about)

> > Also, it doesn't respect the snapshot I want to install my kernels from.
> 
> OK, that seems a bug, I will check
> 
> > I had the following setup: 10.9.1-1-default 14.9.1-1-default 6.6.6-1-default 11.9.1-1-default 15.9.1-1-default 6.9.1-1-default 12.9.1-1-default 5.9.1-1-default 7.9.1-1-default 13.9.1-1-default 6.5.4-1-default 8.9.1-1-default 
> 
> Uhmm I am confused. 10.9.1, 14.9.1 ... you manually put this version in the boot entry?
> 

Yes, I put them manually there. I just wanted to create a behavior where lexicographical ordering would not work (as 10 would be before 6)

> > These kernels are in the esp, each with a entry (snapshot number 300) When I want to install a kernel for the current snapshot (82), it correctly doesn't remove entries from that snapshot. However, it doesn't remove kernel 5.9, but the entries of snapshot 214 and 217:
> 
> The removal of the entries are in date order. So the global oldest is removed first. If will iterate the list in this order, avoiding to remove the ones that we generate a prediction for.
> 

Oh in date order interesting. Makes sense I guess

> What output do you have for `bootctl list`, are they removed in the order showed there?
> 

Yes, then they are as older kernels where added after newer ones. Makes sense now :)

> > When I install a kernel from snapshot 214 now, I would expect sdbootutil to not remove entries from the current snapshot and the snapshot I want to add kernels from. However, the following happens when I want to install kernel from snapshot 214:
> 
> Uhm maybe I need to add a sort_by the date.
> 
> > It just removes the just added entries and kernels again. This is not what I as a user would expect to happen. I would like sdbootutil to either remove the oldest kernels or remove the entries from the oldest snapshots, that are not my root snapshot and the snapshot I want to install kernels from.
> 
> It kept the default, active and last working on MicroOS. Maybe indeed there is a problem in the selection

Ah alright, I'm using Tumbleweed for testing. In general, this is alright, it should just not remove entries I just added (so maybe latest, Default, last-working and selected snapshot? This however already covers 4 snapshots and potential 4 kernels that might not get removed. Why is last-working required? In which case wouldn't that be "active"?)

2024-06-16 15:35 UTC, aplanas commented
> > It is not better that way?
> 
> Of course it is. I would just like the removal to behave as expected by a user (if you have another idea how it should work, that's also valid, but that's what my first question about what it should do was about)

Right. For me the expected behavior was: "remove oldest entry until there is enough free space for the new kernel and initrd, but never remove the active, default and last working entries"

How would you summarize your expectation?

> > It kept the default, active and last working on MicroOS. Maybe indeed there is a problem in the selection
> 
> Ah alright, I'm using Tumbleweed for testing. In general, this is alright, it should just not remove entries I just added (so maybe latest, Default, last-working and selected snapshot? This however already covers 4 snapshots and potential 4 kernels that might not get removed. Why is last-working required? In which case wouldn't that be "active"?)

Ah yes. In Tumbleweed should be: the current and the last two working (pre and post). I am not sure that this is the best selection tho.

In TW the selection can be tricky: there is the snapshot 1 that you should never remove. There is also one that has been created after the update, that contains a pre- and a post-. pre- should represent that "last that was working", and "post-" is the image just after the update. Maybe there is better selection of snapshots in TW.

2024-06-16 18:08 UTC, TobiPeterG commented
> > > It is not better that way?
> > 
> > Of course it is. I would just like the removal to behave as expected by a user (if you have another idea how it should work, that's also valid, but that's what my first question about what it should do was about)
> 
> Right. For me the expected behavior was: "remove oldest entry until there is enough free space for the new kernel and initrd, but never remove the active, default and last working entries"
> 
> How would you summarize your expectation?
> 

My expectation would be: remove the oldest entries (and kernels/initrds) until there's enough space, except they are from my currently running snapshot, the next default snapshot or from the snapshot I want to install from.

> > > It kept the default, active and last working on MicroOS. Maybe indeed there is a problem in the selection
> > 
> > Ah alright, I'm using Tumbleweed for testing. In general, this is alright, it should just not remove entries I just added (so maybe latest, Default, last-working and selected snapshot? This however already covers 4 snapshots and potential 4 kernels that might not get removed. Why is last-working required? In which case wouldn't that be "active"?)
> 
> Ah yes. In Tumbleweed should be: the current and the last two working (pre and post). I am not sure that this is the best selection tho.
> 
> In TW the selection can be tricky: there is the snapshot 1 that you should never remove. There is also one that has been created after the update, that contains a pre- and a post-. pre- should represent that "last that was working", and "post-" is the image just after the update. Maybe there is better selection of snapshots in TW.
> 

Hmm the post-snapshot doesn't need to be kept I guess.
After an update, the post snapshot and current snapshot are identical. So the pre snapshot should be enough I guess, the update can just be re-applied should it be necessary.

2024-06-17 16:37 UTC, aplanas commented
> My expectation would be: remove the oldest entries (and kernels/initrds) until there's enough space, except they are from my currently running snapshot, the next default snapshot or from the snapshot I want to install from.

I did not explicitly added the snapshot from where we are extracting the kernel, but I agree that this must be part of snapshots that should not be touched.

I changed the PR and I try to keep this expectation. Can you test it?

2024-06-18 07:39 UTC, TobiPeterG commented
Well, it's better, but it still doesn't quite work for me. Same setup as above.
Now, when installing from kernel 214, it doesn't remove the just created entries (good). But it doesn't remove other entries that could be removed (the custom entries I added with a snapshot number 300 are not removed)
found kernel 6.4.12-1-default = df1cfa4de2484f72065edd8618d075ff6dc3a7fd
found kernel 6.5.4-1-default = d188a529bfb1f986f9bfbd5ba124683bffa73e41
found kernel 6.6.6-1-default = 5693bb90f9b3f5c84d68e60f12a412746a13e7fb
installing 6.4.12-1-default
generating new initrd
gzip: /var/tmp/dracut.po1PuT/initramfs/.snapshots/214/snapshot/usr/share/kbd/keymaps/xkb/de-nodeadkeys.map.gz: No such file or directory
loading 123 failed
loading 124 failed
loading 125 failed
loading 126 failed
loading 215 failed
loading 216 failed
loading 219 failed
loading 220 failed
loading 222 failed
loading 223 failed
Removing boot entry opensuse-tumbleweed-6.6.6-1-default-218.conf
Removed "/boot/efi/opensuse-tumbleweed/6.6.6-1-default/initrd-4ac962a6dc6a6e08e374d6f50af6730e673767e6"
Removed /boot/efi/loader/entries/opensuse-tumbleweed-6.6.6-1-default-218.conf
loading 123 failed
loading 124 failed
loading 125 failed
loading 126 failed
loading 215 failed
loading 216 failed
loading 219 failed
loading 220 failed
loading 222 failed
loading 223 failed
installed /boot/efi/opensuse-tumbleweed/6.4.12-1-default/linux-df1cfa4de2484f72065edd8618d075ff6dc3a7fd
installed /boot/efi/opensuse-tumbleweed/6.4.12-1-default/initrd-9a53a072a95c098aff9390c57f6118adfecbc69e
installed /boot/efi/loader/entries/opensuse-tumbleweed-6.4.12-1-default-214.conf
installing 6.5.4-1-default
generating new initrd
gzip: /var/tmp/dracut.iNhTBH/initramfs/.snapshots/214/snapshot/usr/share/kbd/keymaps/xkb/de-nodeadkeys.map.gz: No such file or directory
Removing boot entry opensuse-tumbleweed-6.6.6-1-default-221.conf
Removed /boot/efi/loader/entries/opensuse-tumbleweed-6.6.6-1-default-221.conf
Removing boot entry opensuse-tumbleweed-6.6.6-1-default-224.conf
Removed /boot/efi/loader/entries/opensuse-tumbleweed-6.6.6-1-default-224.conf
Removing boot entry opensuse-tumbleweed-6.6.6-1-default-225.conf
Removed "/boot/efi/opensuse-tumbleweed/6.6.6-1-default/initrd-54275e1a2ba49d9eb2362ea498f377bd0339201e"
Removed /boot/efi/loader/entries/opensuse-tumbleweed-6.6.6-1-default-225.conf
Removing boot entry opensuse-tumbleweed-6.6.6-1-default-226.conf
Removed /boot/efi/loader/entries/opensuse-tumbleweed-6.6.6-1-default-226.conf
Removing boot entry opensuse-tumbleweed-6.6.6-1-default-227.conf
Removed /boot/efi/loader/entries/opensuse-tumbleweed-6.6.6-1-default-227.conf
Removing boot entry opensuse-tumbleweed-6.6.6-1-default-228.conf
Removed /boot/efi/loader/entries/opensuse-tumbleweed-6.6.6-1-default-228.conf
Removing boot entry opensuse-tumbleweed-6.6.6-1-default-229.conf
Removed /boot/efi/loader/entries/opensuse-tumbleweed-6.6.6-1-default-229.conf
Removing boot entry opensuse-tumbleweed-6.6.6-1-default-230.conf
Removed /boot/efi/loader/entries/opensuse-tumbleweed-6.6.6-1-default-230.conf
Removing boot entry opensuse-tumbleweed-6.6.6-1-default-231.conf
Removed "/boot/efi/opensuse-tumbleweed/6.6.6-1-default/initrd-333fd9c68a4d8bfcaa03d3dc5cd180dd69501514"
Removed /boot/efi/loader/entries/opensuse-tumbleweed-6.6.6-1-default-231.conf
loading 123 failed
loading 124 failed
loading 125 failed
loading 126 failed
loading 215 failed
loading 216 failed
loading 219 failed
loading 220 failed
loading 222 failed
loading 223 failed
installed /boot/efi/opensuse-tumbleweed/6.5.4-1-default/linux-d188a529bfb1f986f9bfbd5ba124683bffa73e41
installed /boot/efi/opensuse-tumbleweed/6.5.4-1-default/initrd-1cd1b8faf92e17debf037c98bd84fec63f8145d0
installed /boot/efi/loader/entries/opensuse-tumbleweed-6.5.4-1-default-214.conf
installing 6.6.6-1-default
found existing initrd /opensuse-tumbleweed/6.6.6-1-default/initrd-339d0bc20cf786b165c5979859cc09656cd7b881
Error: No free space in /boot/efi for new kernel

The remaining entries
opensuse-tumbleweed-10.9.1-1-default-300.conf
opensuse-tumbleweed-11.9.1-1-default-300.conf
opensuse-tumbleweed-12.9.1-1-default-300.conf
opensuse-tumbleweed-13.9.1-1-default-300.conf
opensuse-tumbleweed-14.9.1-1-default-300.conf
opensuse-tumbleweed-15.9.1-1-default-300.conf
opensuse-tumbleweed-5.9.1-1-default-300.conf
opensuse-tumbleweed-6.4.12-1-default-214.conf
opensuse-tumbleweed-6.5.4-1-default-214.conf
opensuse-tumbleweed-6.6.6-1-default-82.conf
opensuse-tumbleweed-6.9.1-1-default-82.conf
opensuse-tumbleweed-7.9.1-1-default-300.conf
opensuse-tumbleweed-8.9.1-1-default-300.conf
opensuse-tumbleweed-9.9.1-1-default-300.conf

300 is not a default snapshot or anything, they could just be removed.

I test it in a vm, if wanted I can share the vm image with you so you can test it yourself. :)

2024-06-18 07:55 UTC, aplanas commented
I will try to reproduce it. I have the output of your bootctl (thanks!), but I would need to output of snapper too: `snapper --jsonout --no-dbus list --disable-used-space > "$snapperfile"`

2024-06-18 08:23 UTC, TobiPeterG commented
> snapper --jsonout --no-dbus list --disable-used-space >

This is the output:
```
{
  "root": [
    {
      "subvolume": "/",
      "number": 0,
      "default": false,
      "active": false,
      "type": "single",
      "pre-number": null,
      "date": "",
      "user": "root",
      "cleanup": "",
      "description": "current",
      "userdata": null
    },
    {
      "subvolume": "/",
      "number": 78,
      "default": false,
      "active": false,
      "type": "single",
      "pre-number": null,
      "date": "2023-09-29 15:48:44",
      "user": "root",
      "cleanup": "",
      "description": "",
      "userdata": null
    },
    {
      "subvolume": "/",
      "number": 82,
      "default": true,
      "active": true,
      "type": "single",
      "pre-number": null,
      "date": "2023-09-29 15:57:27",
      "user": "root",
      "cleanup": "",
      "description": "writable copy of #78",
      "userdata": null
    },
    {
      "subvolume": "/",
      "number": 120,
      "default": false,
      "active": false,
      "type": "single",
      "pre-number": null,
      "date": "2023-10-05 11:29:24",
      "user": "root",
      "cleanup": "",
      "description": "THis is a test",
      "userdata": null
    },
    {
      "subvolume": "/",
      "number": 203,
      "default": false,
      "active": false,
      "type": "pre",
      "pre-number": null,
      "date": "2023-12-25 08:23:08",
      "user": "root",
      "cleanup": "number",
      "description": "zypp(zypper)",
      "userdata": {
        "important": "yes"
      }
    },
    {
      "subvolume": "/",
      "number": 204,
      "default": false,
      "active": false,
      "type": "post",
      "pre-number": 203,
      "date": "2023-12-25 08:23:36",
      "user": "root",
      "cleanup": "number",
      "description": "",
      "userdata": {
        "important": "yes"
      }
    },
    {
      "subvolume": "/",
      "number": 213,
      "default": false,
      "active": false,
      "type": "pre",
      "pre-number": null,
      "date": "2023-12-25 09:35:00",
      "user": "root",
      "cleanup": "number",
      "description": "zypp(zypper)",
      "userdata": {
        "important": "yes"
      }
    },
    {
      "subvolume": "/",
      "number": 214,
      "default": false,
      "active": false,
      "type": "post",
      "pre-number": 213,
      "date": "2023-12-27 15:01:55",
      "user": "root",
      "cleanup": "number",
      "description": "",
      "userdata": {
        "important": "yes"
      }
    },
    {
      "subvolume": "/",
      "number": 217,
      "default": false,
      "active": false,
      "type": "pre",
      "pre-number": null,
      "date": "2023-12-27 15:12:29",
      "user": "root",
      "cleanup": "number",
      "description": "zypp(zypper)",
      "userdata": {
        "important": "yes"
      }
    },
    {
      "subvolume": "/",
      "number": 218,
      "default": false,
      "active": false,
      "type": "post",
      "pre-number": 217,
      "date": "2023-12-27 15:13:44",
      "user": "root",
      "cleanup": "number",
      "description": "",
      "userdata": {
        "important": "yes"
      }
    },
    {
      "subvolume": "/",
      "number": 221,
      "default": false,
      "active": false,
      "type": "pre",
      "pre-number": null,
      "date": "2024-04-03 20:27:06",
      "user": "root",
      "cleanup": "number",
      "description": "yast sw_single",
      "userdata": null
    },
    {
      "subvolume": "/",
      "number": 224,
      "default": false,
      "active": false,
      "type": "post",
      "pre-number": 221,
      "date": "2024-04-03 20:48:31",
      "user": "root",
      "cleanup": "number",
      "description": "",
      "userdata": null
    },
    {
      "subvolume": "/",
      "number": 225,
      "default": false,
      "active": false,
      "type": "pre",
      "pre-number": null,
      "date": "2024-04-03 21:02:26",
      "user": "root",
      "cleanup": "number",
      "description": "yast sw_single",
      "userdata": null
    },
    {
      "subvolume": "/",
      "number": 226,
      "default": false,
      "active": false,
      "type": "pre",
      "pre-number": null,
      "date": "2024-05-23 00:51:08",
      "user": "root",
      "cleanup": "number",
      "description": "zypp(zypper)",
      "userdata": {
        "important": "yes"
      }
    },
    {
      "subvolume": "/",
      "number": 227,
      "default": false,
      "active": false,
      "type": "post",
      "pre-number": 226,
      "date": "2024-05-23 00:52:06",
      "user": "root",
      "cleanup": "number",
      "description": "",
      "userdata": {
        "important": "yes"
      }
    },
    {
      "subvolume": "/",
      "number": 228,
      "default": false,
      "active": false,
      "type": "pre",
      "pre-number": null,
      "date": "2024-05-23 00:53:24",
      "user": "root",
      "cleanup": "number",
      "description": "zypp(zypper)",
      "userdata": {
        "important": "yes"
      }
    },
    {
      "subvolume": "/",
      "number": 229,
      "default": false,
      "active": false,
      "type": "post",
      "pre-number": 228,
      "date": "2024-05-23 00:53:50",
      "user": "root",
      "cleanup": "number",
      "description": "",
      "userdata": {
        "important": "yes"
      }
    },
    {
      "subvolume": "/",
      "number": 230,
      "default": false,
      "active": false,
      "type": "pre",
      "pre-number": null,
      "date": "2024-05-23 00:54:28",
      "user": "root",
      "cleanup": "number",
      "description": "zypp(zypper)",
      "userdata": {
        "important": "no"
      }
    },
    {
      "subvolume": "/",
      "number": 231,
      "default": false,
      "active": false,
      "type": "post",
      "pre-number": 230,
      "date": "2024-05-23 00:54:51",
      "user": "root",
      "cleanup": "number",
      "description": "",
      "userdata": {
        "important": "no"
      }
    },
    {
      "subvolume": "/",
      "number": 232,
      "default": false,
      "active": false,
      "type": "pre",
      "pre-number": null,
      "date": "2024-05-23 00:55:08",
      "user": "root",
      "cleanup": "number",
      "description": "zypp(zypper)",
      "userdata": {
        "important": "no"
      }
    },
    {
      "subvolume": "/",
      "number": 233,
      "default": false,
      "active": false,
      "type": "post",
      "pre-number": 232,
      "date": "2024-05-23 00:55:15",
      "user": "root",
      "cleanup": "number",
      "description": "",
      "userdata": {
        "important": "no"
      }
    }
  ]
}
```

Please note that snapshot 300 doesn't exist, I just chose a number :)

2024-06-18 12:25 UTC, aplanas commented
I am not sure how you get this results in your tests : ). Maybe I have a different bootctl output?

Basically, with the bootctl and snapper json provided here I have this:

`regex_entries_ids_for_prediction` returns the regular expression that contains the IDs of the snapshots that I want to make predictions for. Those are also the ones that I want too keep. It queries the `snapper` json, and select the active or default ones (ID 82), and the pre and post (232, 233), so the regex is `(:?82|232|233)`

Inspecting the `bootctl` output, not all the entries has `options`, that is the part that refers the subvolume.  For example, the first entry that is shown in your output is "opensuse-tumbleweed-6.6.6-1-default-218.conf" and this one does not have any `options` in you json dump:

```json
  {
    "type": "loader",
    "id": "opensuse-tumbleweed-6.6.6-1-default-218.conf",
    "path": "/sys/firmware/efi/efivars/LoaderEntries-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f",
    "showTitle": "opensuse-tumbleweed-6.6.6-1-default-218.conf",
    "isReported": true,
    "isDefault": false,
    "isSelected": false
  },
  {
    "type": "loader",
    "id": "opensuse-tumbleweed-6.5.4-1-default-218.conf",
    "path": "/sys/firmware/efi/efivars/LoaderEntries-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f",
    "showTitle": "opensuse-tumbleweed-6.5.4-1-default-218.conf",
    "isReported": true,
    "isDefault": false,
    "isSelected": false
  },
```

I am not sure how this was selected! The query that returns the entries that can be removed is this:

```
cat "bootctl.json" | jq '[.[]|select(has("options"))|select(.options|test("root=UUID=bb47a61e-9979-4de9-b1af-e0f06637fbd6 .*rootflags=subvol=@/.snapshots/(:?82|232|233)/snapshot")|not)]'
```

The select check that `options` is present and reverse (`|not`) the select related with the subvolume ID.  With the data provided, the only entries that can be removed are:

```
opensuse-tumbleweed-6.5.4-1-default-214.conf
opensuse-tumbleweed-6.4.12-1-default-214.conf
```

That makes sense, those two are the only entries that has `options` and a subvolume that is not 82, 232 or 233.  The rest of the entries or does not have `options`, or point to the same snapshot (mostly 82, like *-300.conf)

The mystery for me is how you have entries without `options` in the list of being removed!

2024-06-18 18:45 UTC, TobiPeterG commented
> I am not sure how you get this results in your tests : ). Maybe I have a different bootctl output?
> 
> Basically, with the bootctl and snapper json provided here I have this:
> 
> `regex_entries_ids_for_prediction` returns the regular expression that contains the IDs of the snapshots that I want to make predictions for. Those are also the ones that I want too keep. It queries the `snapper` json, and select the active or default ones (ID 82), and the pre and post (232, 233), so the regex is `(:?82|232|233)`
> 
> Inspecting the `bootctl` output, not all the entries has `options`, that is the part that refers the subvolume. For example, the first entry that is shown in your output is "opensuse-tumbleweed-6.6.6-1-default-218.conf" and this one does not have any `options` in you json dump:
> 
> ```json
>   {
>     "type": "loader",
>     "id": "opensuse-tumbleweed-6.6.6-1-default-218.conf",
>     "path": "/sys/firmware/efi/efivars/LoaderEntries-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f",
>     "showTitle": "opensuse-tumbleweed-6.6.6-1-default-218.conf",
>     "isReported": true,
>     "isDefault": false,
>     "isSelected": false
>   },
>   {
>     "type": "loader",
>     "id": "opensuse-tumbleweed-6.5.4-1-default-218.conf",
>     "path": "/sys/firmware/efi/efivars/LoaderEntries-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f",
>     "showTitle": "opensuse-tumbleweed-6.5.4-1-default-218.conf",
>     "isReported": true,
>     "isDefault": false,
>     "isSelected": false
>   },
> ```
> 

The path of these is from an efi variable (see path), so I guess these are the ones that were there on last boot. They were removed when I called sdbootutil add-all-kernels to make space.

> I am not sure how this was selected! The query that returns the entries that can be removed is this:
> 
> ```
> cat "bootctl.json" | jq '[.[]|select(has("options"))|select(.options|test("root=UUID=bb47a61e-9979-4de9-b1af-e0f06637fbd6 .*rootflags=subvol=@/.snapshots/(:?82|232|233)/snapshot")|not)]'
> ```
> 
> The select check that `options` is present and reverse (`|not`) the select related with the subvolume ID. With the data provided, the only entries that can be removed are:
> 
> ```
> opensuse-tumbleweed-6.5.4-1-default-214.conf
> opensuse-tumbleweed-6.4.12-1-default-214.conf
> ```
> 
> That makes sense, those two are the only entries that has `options` and a subvolume that is not 82, 232 or 233. The rest of the entries or does not have `options`, or point to the same snapshot (mostly 82, like *-300.conf)
> 

Ah so the entries that should be removed are selected based on the options string, not the name? That would explain why the 300 entries were not removed :)

> The mystery for me is how you have entries without `options` in the list of being removed!

See above, they were already removed.
Before removal they are listed normally, but also as efi variable.

```
[{"type":"type1","id":"opensuse-tumbleweed-15.9.1-1-default-300.conf","path":"/>
tobias@localhost:/boot/efi/loader/entries> bootctl list --json=short > ~/text
tobias@localhost:/boot/efi/loader/entries> cat ~/text 
[{"type":"type1","id":"opensuse-tumbleweed-15.9.1-1-default-300.conf","path":"/boot/efi/loader/entries/opensuse-tumbleweed-15.9.1-1-default-300.conf","root":"/boot/efi","title":"openSUSE Tumbleweed","showTitle":"openSUSE Tumbleweed (82@15.9.1-1-default)","sortKey":"opensuse-tumbleweed","version":"82@15.9.1-1-default","options":"root=UUID=bb47a61e-9979-4de9-b1af-e0f06637fbd6 splash=silent mitigations=auto quiet security=apparmor rootflags=subvol=@/.snapshots/82/snapshot systemd.machine_id=184769198dfc42a9915b159abff6fb44","linux":"/opensuse-tumbleweed/15.9.1-1-default/linux-6b13316fa0178df1fd6898c8f96f96ab9ecbbbe1","initrd":["/opensuse-tumbleweed/15.9.1-1-default/initrd-4d7dfdd5bb026c5b74d48ecb2bd3935dd4cdd07a"],"isReported":false,"isDefault":false,"isSelected":false},{"type":"type1","id":"opensuse-tumbleweed-14.9.1-1-default-300.conf","path":"/boot/efi/loader/entries/opensuse-tumbleweed-14.9.1-1-default-300.conf","root":"/boot/efi","title":"openSUSE Tumbleweed","showTitle":"openSUSE Tumbleweed (82@14.9.1-1-default)","sortKey":"opensuse-tumbleweed","version":"82@14.9.1-1-default","options":"root=UUID=bb47a61e-9979-4de9-b1af-e0f06637fbd6 splash=silent mitigations=auto quiet security=apparmor rootflags=subvol=@/.snapshots/82/snapshot systemd.machine_id=184769198dfc42a9915b159abff6fb44","linux":"/opensuse-tumbleweed/14.9.1-1-default/linux-6b13316fa0178df1fd6898c8f96f96ab9ecbbbe1","initrd":["/opensuse-tumbleweed/14.9.1-1-default/initrd-4d7dfdd5bb026c5b74d48ecb2bd3935dd4cdd07a"],"isReported":false,"isDefault":false,"isSelected":false},{"type":"type1","id":"opensuse-tumbleweed-13.9.1-1-default-300.conf","path":"/boot/efi/loader/entries/opensuse-tumbleweed-13.9.1-1-default-300.conf","root":"/boot/efi","title":"openSUSE Tumbleweed","showTitle":"openSUSE Tumbleweed (82@13.9.1-1-default)","sortKey":"opensuse-tumbleweed","version":"82@13.9.1-1-default","options":"root=UUID=bb47a61e-9979-4de9-b1af-e0f06637fbd6 splash=silent mitigations=auto quiet security=apparmor rootflags=subvol=@/.snapshots/82/snapshot systemd.machine_id=184769198dfc42a9915b159abff6fb44","linux":"/opensuse-tumbleweed/13.9.1-1-default/linux-6b13316fa0178df1fd6898c8f96f96ab9ecbbbe1","initrd":["/opensuse-tumbleweed/13.9.1-1-default/initrd-4d7dfdd5bb026c5b74d48ecb2bd3935dd4cdd07a"],"isReported":false,"isDefault":false,"isSelected":false},{"type":"type1","id":"opensuse-tumbleweed-12.9.1-1-default-300.conf","path":"/boot/efi/loader/entries/opensuse-tumbleweed-12.9.1-1-default-300.conf","root":"/boot/efi","title":"openSUSE Tumbleweed","showTitle":"openSUSE Tumbleweed (82@12.9.1-1-default)","sortKey":"opensuse-tumbleweed","version":"82@12.9.1-1-default","options":"root=UUID=bb47a61e-9979-4de9-b1af-e0f06637fbd6 splash=silent mitigations=auto quiet security=apparmor rootflags=subvol=@/.snapshots/82/snapshot systemd.machine_id=184769198dfc42a9915b159abff6fb44","linux":"/opensuse-tumbleweed/12.9.1-1-default/linux-6b13316fa0178df1fd6898c8f96f96ab9ecbbbe1","initrd":["/opensuse-tumbleweed/12.9.1-1-default/initrd-4d7dfdd5bb026c5b74d48ecb2bd3935dd4cdd07a"],"isReported":false,"isDefault":false,"isSelected":false},{"type":"type1","id":"opensuse-tumbleweed-11.9.1-1-default-300.conf","path":"/boot/efi/loader/entries/opensuse-tumbleweed-11.9.1-1-default-300.conf","root":"/boot/efi","title":"openSUSE Tumbleweed","showTitle":"openSUSE Tumbleweed (82@11.9.1-1-default)","sortKey":"opensuse-tumbleweed","version":"82@11.9.1-1-default","options":"root=UUID=bb47a61e-9979-4de9-b1af-e0f06637fbd6 splash=silent mitigations=auto quiet security=apparmor rootflags=subvol=@/.snapshots/82/snapshot systemd.machine_id=184769198dfc42a9915b159abff6fb44","linux":"/opensuse-tumbleweed/11.9.1-1-default/linux-6b13316fa0178df1fd6898c8f96f96ab9ecbbbe1","initrd":["/opensuse-tumbleweed/11.9.1-1-default/initrd-4d7dfdd5bb026c5b74d48ecb2bd3935dd4cdd07a"],"isReported":false,"isDefault":false,"isSelected":false},{"type":"type1","id":"opensuse-tumbleweed-10.9.1-1-default-300.conf","path":"/boot/efi/loader/entries/opensuse-tumbleweed-10.9.1-1-default-300.conf","root":"/boot/efi","title":"openSUSE Tumbleweed","showTitle":"openSUSE Tumbleweed (82@10.9.1-1-default)","sortKey":"opensuse-tumbleweed","version":"82@10.9.1-1-default","options":"root=UUID=bb47a61e-9979-4de9-b1af-e0f06637fbd6 splash=silent mitigations=auto quiet security=apparmor rootflags=subvol=@/.snapshots/82/snapshot systemd.machine_id=184769198dfc42a9915b159abff6fb44","linux":"/opensuse-tumbleweed/10.9.1-1-default/linux-6b13316fa0178df1fd6898c8f96f96ab9ecbbbe1","initrd":["/opensuse-tumbleweed/10.9.1-1-default/initrd-4d7dfdd5bb026c5b74d48ecb2bd3935dd4cdd07a"],"isReported":false,"isDefault":false,"isSelected":false},{"type":"type1","id":"opensuse-tumbleweed-9.9.1-1-default-300.conf","path":"/boot/efi/loader/entries/opensuse-tumbleweed-9.9.1-1-default-300.conf","root":"/boot/efi","title":"openSUSE Tumbleweed","showTitle":"openSUSE Tumbleweed (82@9.9.1-1-default)","s [...]

2024-06-18 19:07 UTC, aplanas commented
> The path of these is from an efi variable (see path), so I guess these are the ones that were there on last boot. They were removed when I called sdbootutil add-all-kernels to make space.

So I understand that the first bootctl.json that you send was not the original one used before the removal, so the test that I did would not match with your results. But I still do not understand why there is still an element listed for a removed entry.

Did we test something useful? Are you still convinced that the code is not doing what it is expected?

> Ah so the entries that should be removed are selected based on the options string, not the name?

Right. The name is not the relevant part, but what snapshot is referencing to.

2024-06-18 19:08 UTC, aplanas commented
@TobiPeterG do you agree to merge this, or you want to make more tests?

2024-06-18 20:16 UTC, TobiPeterG commented
Adjusted my tests, they work now :)

I'll have a look at the code now :)

2024-06-18 20:50 UTC, TobiPeterG requested changes
Please have a look, I think me can make the code a bit slimmer and improve resuablilty. :)

2024-06-18 20:50 UTC, TobiPeterG commented on sdbootutil
> +
Is it really neccessary to add a new function for this?
Couldn't we add a second optional parameter for the update_entries_for_snapshot function and pass the string "invert" to it?
This would also remove code duplication.

2024-06-18 20:50 UTC, TobiPeterG commented on sdbootutil
> +}
You're using "echo" quite often to return values from variables. Ludwig didn't really do that, he wrote variables/outputs into files or used global variables. Do you know why?

2024-06-18 20:50 UTC, TobiPeterG commented on sdbootutil
> +}
maybe the function "regex_entries_ids_for_prediction" should be renamed as it's not only used for prediction anymore.

2024-06-18 20:50 UTC, TobiPeterG commented on sdbootutil
> +	# the snapshot from where we are installing the kernel
When I understood you correctly, we don't want to remove snapshot 1. Wouldn't the current implementation potentially remove snapshot 1 from the ESP? Is that an issue or don't we care as long as snapper still has it?
Or did I misunderstand you?

2024-06-18 20:50 UTC, TobiPeterG commented on sdbootutil
> +}
This function and select_entries_for_prediction should be unfifiable, especially when you remove the "update_entries_for_snapshot_invert" function.

2024-06-18 20:50 UTC, TobiPeterG commented on sdbootutil
> +}
How does this take into account that we might need to create a folder for the kernel?
We could have an edge case were we have exactly as much space available on the ESP as the files are big, but need to create the folders for them as well. If I'm not mistaken, a folder needs 4KB of space on an EFI parition.
I added it in my PR like this:
```
	if [ ! -d "$boot_root${dst%/*}" ]; then
		((src_size_kb+=4))
	fi
```

The issue is: We need to know the destination of the files to do that.

2024-06-18 20:50 UTC, TobiPeterG commented on sdbootutil
> +}
We could add the 4KB slack for every kernel we install, but this might also hit an edge case where we calculate with the folder, think it's not enough, but the folder already exists and without it it would exactly fit.

2024-06-18 20:55 UTC, aplanas commented on sdbootutil
> +
I did added the optional parameter at the beginning, but this confuses a bit the code. Boolean parameters are kind of weird. Instead of "invert" (a random string) I can use "not", "0", "1", "true", "false" or anything mostly.

So I decided to wrap this weirdness in a named function that is explicit in what it does.

2024-06-18 21:01 UTC, aplanas commented on sdbootutil
> +}
Ludwig uses this too, for example in `menuheight()` or in `find_conf_file()`.

The global variables is for more complex structs (arrays, list), or for costly operations (snapper list, bootctl list).

The reason (besides the limitation of bash of not being able to return real data, only status), is the subshell creation. For each function that we want to get the printed value via echo, we need to do `$()`, that triggers a new subshell.

I personally have a different style ... Echo is bad (is very easy to pollute the stdout and break the return value), but makes the code clear IMHO.

2024-06-18 21:05 UTC, aplanas commented on sdbootutil
> +}
That makes sense. Honestly, the IDs returned are always the ones that I want to make predictions for ... 

Maybe `regex_entries_ids_for_predictions_ext`? The ext, is because can be extended via an optional parameter.

I am very bad with names, do you have a suggestion? : )))

2024-06-18 21:09 UTC, aplanas commented on sdbootutil
> +	# the snapshot from where we are installing the kernel
If snapshot 1 is active or default, no we cannot remove it. But if we do a rollback, we are not anymore in snapshot 1 and this can be removed eventually (by snapper itself for example).

2024-06-18 21:12 UTC, aplanas commented on sdbootutil
> +}
Can you clarify?

select_entries_for_free_space is the invert of select_entries_for_prediction ...

2024-06-18 21:18 UTC, aplanas commented on sdbootutil
> +}
Uhmm... FAT32 contains the file and directory metadata in the FAT sectors IIRC. So this does not consume space.  It is a pre-allocated table. In NTFS seems that the metadata space is 1KB, tho.

Do you have a reference for the 4KB in FAT32?

In any case I added one extra KB during the rounding when calculating the consumed space, and I did not added it when calculating the free space. That should take account for any required extra space (like the .conf file)

2024-06-18 21:37 UTC, TobiPeterG commented on sdbootutil
> +
Hmm I see. Why don't we pass 'not' as parameter and add it to the jq command if it is set? This would also allow to potentially use other filters as well in the future.

2024-06-18 21:42 UTC, TobiPeterG commented on sdbootutil
> +}
Alright, thanks :)
Random idea: I see that a global variable is not really useful for single data points, but echo is also not really optimal. An idea would be to add a global dynamic array with a key and value so we can add variables to it with its value and access it. This wouldn't create a bunch of global variables that are only used once. However, I don't know the runtime implications of these operations. It would also still not be a nice solution, but it seems like bash doesn't really have a nice solution for this.

But I see why you might want to stick with echo

2024-06-18 21:46 UTC, TobiPeterG commented on sdbootutil
> +}
why the "for_predictions" postfix? The function is also used to find entries for removal. 
Why not just "regex_entries_ids" or, IMO a bit nicer: "filter_entries_ids" I'm not even sure if the "ids" postfix is required.

2024-06-18 22:01 UTC, TobiPeterG commented on sdbootutil
> +}
Sure :)

What I thought:
```
select_entries_for_free_space()
{
	local snapshot="$1"
	update_entries_for_snapshot_invert "$(regex_entries_ids_for_prediction "$snapshot")"
}
```
and
```
# TODO: Maybe share this code outside
select_entries_for_prediction()
{
	update_entries_for_snapshot "$(regex_entries_ids_for_prediction)"
}
```

could become one function:

select_entries()
{
	local snapshot="$1"
	local filter="${2:-}"
	update_entries_for_snapshot "$(regex_entries_ids_for_prediction $snapshot)" "$filter"
}

with

```
update_entries_for_snapshot()
{
	local n="$1"
	local filter="${2:-}"
	update_entries_for_subvol "${subvol_prefix}/.snapshots/$n/snapshot" "$filter"
}
```

and 

update_entries_for_subvol()
{
	local subvol="$1"
	local filter="${2:-}"

	update_entries jq "[.[]|select(has(\"options\"))|select(.options|test(\"root=UUID=$root_uuid .*rootflags=subvol=$subvol\")${filter:+|$filter})]"
}

Now you can call
`select_entries` instead of `select_entries_for_prediction`,
`select_entries "$snapshot" "not"` instead of `select_entries_for_free_space "$snapshot"`

And it would remove `update_entries_for_snapshot_invert`

(This is untested and just an idea)


Btw. doesn't the current implementation only work when btrfs and snapshots are used? What if e.g. ext4 is used? The $snapshot" variable is not available then.

2024-06-18 22:08 UTC, TobiPeterG commented on sdbootutil
> +}
I did some tests, I re-ran them and it seems I mis-interpreted them:
```
sudo findmnt -n -b -o AVAIL --target "/boot/efi"
68116480
sudo mkdir test
sudo findmnt -n -b -o AVAIL --target "/boot/efi"
68112384
sudo mkdir test2
sudo findmnt -n -b -o AVAIL --target "/boot/efi"
68108288
```

The space actually increases by 4 Bytes (lol) with each folder, so you're right, we don't need to take them into account :)

2024-06-18 22:09 UTC, TobiPeterG commented on sdbootutil
> +}
The conf files are about 1.4 to 1.6 KB in size on my machine, so maybe allocate 2KB for each entry?

2024-06-19 06:08 UTC, aplanas commented on sdbootutil
> +
Yes. I will do that.

2024-06-19 06:11 UTC, aplanas commented on sdbootutil
> +}
Another idiom that is used is [nameref](https://www.gnu.org/software/bash/manual/bash.html#Shell-Parameters) (`local -n`). It is specific for bash, it seems.

2024-06-19 06:15 UTC, aplanas commented on sdbootutil
> +}
Ah yes. You mean unifiable. I prefer the current naming. Mixing the code with optional parameters is OK if the function is really a general case, but in this case seems to me that is by accident.

> Btw. doesn't the current implementation only work when btrfs and snapshots are used? What if e.g. ext4 is used? The $snapshot" variable is not available then.

Good point. I will check this.

2024-06-19 07:15 UTC, aplanas commented on sdbootutil
> +
done

2024-06-19 07:18 UTC, aplanas commented on sdbootutil
> +}
uhm no, the ids that returns are the one selected only to make predictions for. This regex is used later to select the ones that are NOT for prediction (|not), those are the one for removal. So this function does not return the ids that are for removal.

2024-06-19 07:21 UTC, aplanas commented on sdbootutil
> +}
Are you sure? `ls -lah` report me that the biggest one is 743 bytes

2024-06-19 07:25 UTC, aplanas commented on sdbootutil
> +}
https://github.com/openSUSE/sdbootutil/issues/100

2024-06-19 07:26 UTC, aplanas commented
@TobiPeterG thanks for the reviews!

2024-06-19 07:27 UTC, merged

2024-06-19 10:15 UTC, TobiPeterG commented on sdbootutil
> +}
Oh you're right, I probably should stop working after 11pm, sorry

2024-06-19 10:18 UTC, TobiPeterG commented on sdbootutil
> +
Have you pushed the changes?

2024-06-19 11:23 UTC, aplanas commented on sdbootutil
> +
Oh my ... I cannot believe it :' (. No, I did not.

Thanks that `reflog` saved the work. It is now in `main` via https://github.com/openSUSE/sdbootutil/pull/101